<?php defined('BASEPATH') OR exit('No direct script access allowed');

class Home extends Public_Controller
{
	function __construct()
	{
		parent::__construct();
	}

	public function index()
	{
		$this->add_external_js(array(
            "assets/chart/chart.js",
            "assets/home/js/home.js",
        ));
        $this->add_external_css(array(
        ));

		$data = $this->includes;

		$data['title_menu'] = 'Dashboard';

		$content = null;
		$data['view'] = $this->load->view('home/dashboard', $content, true);

		$this->load->view($this->template, $data);
	}

	public function getDataPenjualan()
	{
		$today = date('Y-m-d');

		$m_branch = new \Model\Storage\Branch_model();
		$d_branch = $m_branch->get();

		$_list_hari = null;
		$_list_outlet = null;
		if ( $d_branch->count() > 0 ) {
			$d_branch = $d_branch->toArray();

			$idx = 0;
			foreach ($d_branch as $k_branch => $v_branch) {
				$prev_date = prev_date($today, 13);

				$list_total = [];

				$_list_outlet[ $v_branch['nama'] ]['nama'] = $v_branch['nama'];
				if ( $idx == 0 ) {
					$_list_outlet[ $v_branch['nama'] ]['warna']['r'] = 255;
					$_list_outlet[ $v_branch['nama'] ]['warna']['g'] = 0;
					$_list_outlet[ $v_branch['nama'] ]['warna']['b'] = 0;
				} else {
					$_list_outlet[ $v_branch['nama'] ]['warna']['r'] = 0;
					$_list_outlet[ $v_branch['nama'] ]['warna']['g'] = 0;
					$_list_outlet[ $v_branch['nama'] ]['warna']['b'] = 255;
				}

				$idx++;

				for ($i=0; $i < 14; $i++) {
					$_list_hari[strtoupper(tglIndonesia($prev_date, '-', ' '))] = substr(strtoupper(tglIndonesia($prev_date, '-', ' ')), 0, 6);

					$start_date = $prev_date.' 00:00:00';
					$end_date = $prev_date.' 23:59:29';

					$sql = "
						select sum(j.grand_total) as total from jual j
						where
							j.mstatus = 1 and
							j.tgl_trans between '".$start_date."' and '".$end_date."' and
							j.branch = '".$v_branch['kode_branch']."'
						group by
							j.branch
					";

					$m_jual = new \Model\Storage\Jual_model();
					$d_jual = $m_jual->hydrateRaw($sql);

					if ( $d_jual->count() > 0 ) {
						$d_jual = $d_jual->toArray();

						foreach ($d_jual as $k_jual => $v_jual) {
							$list_total[] = $v_jual['total'];
						}
					} else {
						$list_total[] = 0;
					}

					$_list_outlet[ $v_branch['nama'] ]['list_total'] = $list_total;

					$prev_date = next_date( $prev_date );
				}
			}
		}

		if ( !empty($_list_hari) && !empty($_list_outlet) ) {
			$list_hari = null;
			foreach ($_list_hari as $k_lh => $v_lh) {
				$list_hari[] = $v_lh;
			}

			$list_outlet = null;
			foreach ($_list_outlet as $k_lo => $v_lo) {
				$list_outlet[] = $v_lo;
			}

			$this->result['status'] = 1;
			$this->result['content'] = array(
				'list_hari' => $list_hari,
				'list_outlet' => $list_outlet
			);
		} else {
			$this->result['status'] = 0;
		}

		display_json( $this->result );
	}

	public function list_notif()
	{
		$notif = null;
		$arr_fitur = $this->session->userdata()['Fitur']; 
		foreach ($arr_fitur as $key => $v_fitur) {
			foreach ($v_fitur['detail'] as $key => $v_mdetail) {
				$akses = hakAkses('/'.$v_mdetail['path_detfitur']);
				if ( $akses['a_ack'] == 1 ) {
					$status = getStatus('submit');

					$data = Modules::run( $v_mdetail['path_detfitur'].'/model', $status)->first();

					$notif[$v_mdetail['path_detfitur']] = $data->toArray();
					$notif[$v_mdetail['path_detfitur']]['path'] = $v_mdetail['path_detfitur'];
					$notif[$v_mdetail['path_detfitur']]['nama_fitur'] = $v_mdetail['nama_detfitur'];

				} else if ( $akses['a_approve'] == 1 ) {
					$status = getStatus('ack');

					$data = Modules::run( $v_mdetail['path_detfitur'].'/model', $status)->first();

					$notif[$v_mdetail['path_detfitur']] = $data->toArray();
					$notif[$v_mdetail['path_detfitur']]['path'] = $v_mdetail['path_detfitur'];
					$notif[$v_mdetail['path_detfitur']]['nama_fitur'] = $v_mdetail['nama_detfitur'];
				}
			}
        }

        return $notif;
	}

	public function tes(){
		$data = array(
			'Acar',
			'Acar',
			'Acar',
			'Acar',
			'Acar',
			'Acar',
			'Acar',
			'American breakfast',
			'American breakfast',
			'American breakfast',
			'American breakfast',
			'American breakfast',
			'American breakfast',
			'American breakfast',
			'American breakfast',
			'American breakfast',
			'American breakfast',
			'American breakfast',
			'American breakfast',
			'American breakfast',
			'Ayam Aroma',
			'Ayam Aroma',
			'Ayam Aroma',
			'Ayam Aroma',
			'Ayam Aroma',
			'Ayam Aroma',
			'Ayam Aroma',
			'Ayam Aroma',
			'Ayam Aroma',
			'Ayam Aroma',
			'Ayam Aroma',
			'Ayam Aroma',
			'Ayam Aroma',
			'Ayam Aroma',
			'Ayam Aroma',
			'Ayam Cabe Garam',
			'Ayam Cabe Garam',
			'Ayam Cabe Garam',
			'Ayam Cabe Garam',
			'Ayam Cabe Garam',
			'Ayam Cabe Garam',
			'Ayam Cabe Garam',
			'Ayam Cabe Garam',
			'Ayam Cabe Garam',
			'Ayam Cabe Garam',
			'Ayam Cabe Garam',
			'Ayam Cabe Garam',
			'Ayam Cabe Garam',
			'Ayam Cabe Garam',
			'Ayam Cabe Garam',
			'Ayam Dabu Dabu',
			'Ayam Dabu Dabu',
			'Ayam Dabu Dabu',
			'Ayam Dabu Dabu',
			'Ayam Dabu Dabu',
			'Ayam Dabu Dabu',
			'Ayam Dabu Dabu',
			'Ayam Dabu Dabu',
			'Ayam Dabu Dabu',
			'Ayam Dabu Dabu',
			'Ayam Dabu Dabu',
			'Ayam Dabu Dabu',
			'Ayam Dabu Dabu',
			'Ayam Dabu Dabu',
			'Ayam Dabu Dabu',
			'Ayam goreng biasa (reguler)',
			'Ayam goreng biasa (reguler)',
			'Ayam goreng biasa (reguler)',
			'Ayam goreng biasa (reguler)',
			'Ayam goreng biasa (reguler)',
			'Ayam goreng biasa (reguler)',
			'Ayam goreng biasa (reguler)',
			'Ayam goreng biasa (reguler)',
			'Ayam goreng biasa (reguler)',
			'Ayam penyet Graha',
			'Ayam penyet Graha',
			'Ayam penyet Graha',
			'Ayam penyet Graha',
			'Ayam penyet Graha',
			'Ayam penyet Graha',
			'Ayam penyet Graha',
			'Ayam penyet Graha',
			'Ayam penyet Graha',
			'Ayam penyet Graha',
			'Ayam penyet Graha',
			'Ayam penyet Graha',
			'Ayam penyet Graha',
			'Ayam penyet Graha',
			'Ayam penyet Graha',
			'ayam saus jahe (nasi hainan)',
			'ayam saus jahe (nasi hainan)',
			'ayam saus jahe (nasi hainan)',
			'ayam saus jahe (nasi hainan)',
			'ayam saus jahe (nasi hainan)',
			'ayam saus jahe (nasi hainan)',
			'ayam saus jahe (nasi hainan)',
			'ayam saus jahe (nasi hainan)',
			'ayam saus jahe (nasi hainan)',
			'ayam saus jahe (nasi hainan)',
			'ayam saus jahe (nasi hainan)',
			'ayam saus jahe (nasi hainan)',
			'ayam saus jahe (nasi hainan)',
			'ayam saus jahe (nasi hainan)',
			'ayam saus jahe (nasi hainan)',
			'Bacon slice',
			'Bakso Campur',
			'Bakso Campur',
			'Bakso Campur',
			'Bakso Campur',
			'Bakso Campur',
			'Bakso Campur',
			'Bakso Campur',
			'Bakso Campur',
			'Bakso Campur',
			'Bakso Campur',
			'Bakso Campur',
			'Bakso Campur',
			'Bakso Campur',
			'Batagor Bandung',
			'Batagor Bandung',
			'Batagor Bandung',
			'Batagor Bandung',
			'Batagor Bandung',
			'Batagor Bandung',
			'Batagor Bandung',
			'Beef Black Pepper',
			'Beef Black Pepper',
			'Beef Black Pepper',
			'Beef Black Pepper',
			'Beef Black Pepper',
			'Beef Black Pepper',
			'Beef Black Pepper',
			'Beef Honey Sauce',
			'Beef Honey Sauce',
			'Beef Honey Sauce',
			'Beef Honey Sauce',
			'Beef Honey Sauce',
			'Beef Honey Sauce',
			'Beef Honey Sauce',
			'Beef Teriyaki',
			'Beef Teriyaki',
			'Beef Teriyaki',
			'Beef Teriyaki',
			'Beef Teriyaki',
			'Beef Teriyaki',
			'Beef Teriyaki',
			'Beef Teriyaki',
			'Beef Teriyaki',
			'Beef Teriyaki',
			'Beef Teriyaki',
			'Beef Teriyaki',
			'Beef Teriyaki',
			'Beef Teriyaki',
			'Beef Teriyaki',
			'Beef Teriyaki',
			'Beef Teriyaki',
			'Bihun Goreng Ayam',
			'Bihun Goreng Ayam',
			'Bihun Goreng Ayam',
			'Bihun Goreng Ayam',
			'Bihun Goreng Ayam',
			'Bihun Goreng Ayam',
			'Bihun Goreng Ayam',
			'Bihun Goreng Ayam',
			'Bihun Goreng Ayam',
			'Bihun Goreng Beef',
			'Bihun Goreng Beef',
			'Bihun Goreng Beef',
			'Bihun Goreng Beef',
			'Bihun Goreng Beef',
			'Bihun Goreng Beef',
			'Bihun Goreng Beef',
			'Bihun Goreng Beef',
			'Bihun Goreng Beef',
			'Bihun Goreng Jawa',
			'Bihun Goreng Jawa',
			'Bihun Goreng Jawa',
			'Bihun Goreng Jawa',
			'Bihun Goreng Jawa',
			'Bihun Goreng Jawa',
			'Bihun Goreng Jawa',
			'Bihun Goreng Jawa',
			'Bihun Goreng Jawa',
			'Bihun Goreng Jawa',
			'Bihun hot plate ayam',
			'Bihun hot plate ayam',
			'Bihun hot plate ayam',
			'Bihun hot plate ayam',
			'Bihun hot plate ayam',
			'Bihun hot plate ayam',
			'Bihun hot plate ayam',
			'Bihun hot plate ayam',
			'Bihun hot plate ayam',
			'Bihun hot plate ayam',
			'Bihun hot plate ayam',
			'Bihun hot plate ayam',
			'Bihun hot plate ayam',
			'Bihun hot plate ayam',
			'Bihun hot plate ayam',
			'Bihun hot plate ayam',
			'Bihun hot plate ayam',
			'Bihun hot plate ayam',
			'Bihun Hot plate beef',
			'Bihun Hot plate beef',
			'Bihun Hot plate beef',
			'Bihun Hot plate beef',
			'Bihun Hot plate beef',
			'Bihun Hot plate beef',
			'Bihun Hot plate beef',
			'Bihun Hot plate beef',
			'Bihun Hot plate beef',
			'Bihun Hot plate beef',
			'Bihun Hot plate beef',
			'Bihun Hot plate beef',
			'Bihun Hot plate beef',
			'Bihun Hot plate beef',
			'Bihun Hot plate beef',
			'Bihun Hot plate beef',
			'Bihun Hot plate beef',
			'Bihun Hot plate beef',
			'Bihun Hot plate beef',
			'Bihun Hot plate seafood',
			'Bihun Hot plate seafood',
			'Bihun Hot plate seafood',
			'Bihun Hot plate seafood',
			'Bihun Hot plate seafood',
			'Bihun Hot plate seafood',
			'Bihun Hot plate seafood',
			'Bihun Hot plate seafood',
			'Bihun Hot plate seafood',
			'Bihun Hot plate seafood',
			'Bihun Hot plate seafood',
			'Bihun Hot plate seafood',
			'Bihun Hot plate seafood',
			'Bihun Hot plate seafood',
			'Bihun Hot plate seafood',
			'Bihun Hot plate seafood',
			'Bihun Hot plate seafood',
			'Bihun Hot plate seafood',
			'Bihun Hot plate seafood',
			'Bihun Hot plate seafood',
			'Bihun kocok medan',
			'Bihun kocok medan',
			'Bihun kocok medan',
			'Bihun kocok medan',
			'Bihun kocok medan',
			'Bihun kocok medan',
			'Bihun kocok medan',
			'Bihun kocok medan',
			'Bihung Goreng Seafood',
			'Bihung Goreng Seafood',
			'Bihung Goreng Seafood',
			'Bihung Goreng Seafood',
			'Bihung Goreng Seafood',
			'Bihung Goreng Seafood',
			'Bihung Goreng Seafood',
			'Bihung Goreng Seafood',
			'Bihung Goreng Seafood',
			'Bihung Goreng Seafood',
			'Bihung Goreng Seafood',
			'Buah Segar',
			'Buah Segar',
			'Buah Segar',
			'Buah Segar',
			'Buah Segar',
			'Bubur Ayam',
			'Bubur Ayam',
			'Bubur Ayam',
			'Bubur Ayam',
			'Bubur Ayam',
			'Bubur Ayam',
			'Bubur Ayam',
			'Bubur Ayam',
			'Bubur Ayam',
			'Bubur Ayam',
			'Bubur Ayam',
			'Bubur Ayam',
			'Bubur Ayam',
			'Bubur Ayam',
			'Bubur Ayam Charsiu',
			'Bubur Ayam Charsiu',
			'Bubur Ayam Charsiu',
			'Bubur Ayam Charsiu',
			'Bubur Ayam Charsiu',
			'Bubur Ayam Charsiu',
			'Bubur Ayam Charsiu',
			'Bubur Ayam Charsiu',
			'Bubur Ayam Charsiu',
			'Bubur Ayam Charsiu',
			'Bubur Ayam Charsiu',
			'Bubur Ayam Charsiu',
			'Bubur Ayam Charsiu',
			'Bubur Ayam Charsiu',
			'Buncis Singapore',
			'Buncis Singapore',
			'Buncis Singapore',
			'Buncis Singapore',
			'Butter rice chicken black pepper sauce',
			'Butter rice chicken black pepper sauce',
			'Butter rice chicken black pepper sauce',
			'Butter rice chicken black pepper sauce',
			'Butter rice chicken black pepper sauce',
			'Butter rice chicken black pepper sauce',
			'Butter rice chicken black pepper sauce',
			'Butter rice chicken black pepper sauce',
			'Butter rice chicken black pepper sauce',
			'Butter rice chicken black pepper sauce',
			'Butter rice chicken black pepper sauce',
			'Butter/Jam',
			'calamari ring',
			'calamari ring',
			'calamari ring',
			'calamari ring',
			'calamari ring',
			'calamari ring',
			'calamari ring',
			'calamari ring',
			'Cap Cay Goreng',
			'Cap Cay Goreng',
			'Cap Cay Goreng',
			'Cap Cay Goreng',
			'Cap Cay Goreng',
			'Cap Cay Goreng',
			'Cap Cay Goreng',
			'Cap Cay Goreng',
			'Cap Cay Goreng',
			'Cap Cay Goreng',
			'Cap Cay Goreng',
			'Cap Cay Goreng',
			'Cap Cay Goreng',
			'Cap Cay Goreng',
			'Cap Cay Goreng',
			'Cap Cay Goreng',
			'Cheese cedar',
			'Cheese Sandwich',
			'Cheese Sandwich',
			'Cheese Sandwich',
			'Cheese Sandwich',
			'Cheese Sandwich',
			'Cheese Sandwich',
			'Cheese Sandwich',
			'Cheese Sandwich',
			'Cheese Sandwich',
			'Cheese Sandwich',
			'Cheese Sandwich',
			'Chicken BBQ pizza u 24',
			'Chicken BBQ pizza u 24',
			'Chicken BBQ pizza u 24',
			'Chicken BBQ pizza u 24',
			'Chicken BBQ pizza u 24',
			'Chicken BBQ pizza u 24',
			'Chicken BBQ pizza u 24',
			'Chicken BBQ pizza u 24',
			'Chicken BBQ pizza u 24',
			'Chicken BBQ pizza u 24',
			'Chicken Steak',
			'Chicken Steak',
			'Chicken Steak',
			'Chicken Steak',
			'Chicken Steak',
			'Chicken Steak',
			'Chicken Steak',
			'Chicken Steak',
			'Club Sandwich ayam',
			'Club Sandwich ayam',
			'Club Sandwich ayam',
			'Club Sandwich ayam',
			'Club Sandwich ayam',
			'Club Sandwich ayam',
			'Club Sandwich ayam',
			'Club Sandwich ayam',
			'Club Sandwich ayam',
			'Club Sandwich ayam',
			'Club Sandwich ayam',
			'Club Sandwich ayam',
			'Club Sandwich ayam',
			'Club sandwich Daging Sapi',
			'Club sandwich Daging Sapi',
			'Club sandwich Daging Sapi',
			'Club sandwich Daging Sapi',
			'Club sandwich Daging Sapi',
			'Club sandwich Daging Sapi',
			'Club sandwich Daging Sapi',
			'Club sandwich Daging Sapi',
			'Club sandwich Daging Sapi',
			'Club sandwich Daging Sapi',
			'Club sandwich Daging Sapi',
			'Club sandwich Daging Sapi',
			'Club sandwich Daging Sapi',
			'Cumi Bakar saus quilin',
			'Cumi Bakar saus quilin',
			'Cumi Bakar saus quilin',
			'Cumi Bakar saus quilin',
			'Cumi Bakar saus quilin',
			'Cumi Bakar saus quilin',
			'Cumi Bakar saus quilin',
			'Cumi Bakar saus quilin',
			'Cumi Bakar saus quilin',
			'Cumi Bakar saus quilin',
			'Cumi Bakar saus quilin',
			'Cumi Bakar saus quilin',
			'Cumi Bakar saus quilin',
			'Cumi Bakar saus quilin',
			'Cumi Bakar saus quilin',
			'Cumi Bakar saus quilin',
			'Curley cheese fries',
			'Curley cheese fries',
			'Dorang Bakar/Reguler',
			'Dorang Bakar/Reguler',
			'Dorang Bakar/Reguler',
			'Dorang Bakar/Reguler',
			'Dorang Bakar/Reguler',
			'Dorang Bakar/Reguler',
			'Dorang Bakar/Reguler',
			'Dorang Bakar/Reguler',
			'Dorang Bakar/Reguler',
			'Dorang Bakar/Reguler',
			'Dorang Dabu Dabu (L)',
			'Dorang Dabu Dabu (L)',
			'Dorang Dabu Dabu (L)',
			'Dorang Dabu Dabu (L)',
			'Dorang Dabu Dabu (L)',
			'Dorang Dabu Dabu (L)',
			'Dorang Dabu Dabu (L)',
			'Dorang Dabu Dabu (L)',
			'Dorang Dabu Dabu (M)',
			'Dorang Dabu Dabu (M)',
			'Dorang Dabu Dabu (M)',
			'Dorang Dabu Dabu (M)',
			'Dorang Dabu Dabu (M)',
			'Dorang Dabu Dabu (M)',
			'Dorang Dabu Dabu (M)',
			'Dorang Dabu Dabu (M)',
			'Dorang penyet',
			'Dorang penyet',
			'Dorang penyet',
			'Dorang penyet',
			'Dorang penyet',
			'Dorang penyet',
			'Dorang penyet',
			'Dorang penyet',
			'Dorang penyet',
			'Dorang penyet',
			'Dorang penyet',
			'Dorang penyet',
			'Dorang penyet',
			'Edditional ayam goreng',
			'Edditional ayam goreng',
			'Edditional ayam goreng',
			'Edditional ayam goreng',
			'Edditional ayam goreng',
			'Edditional ayam goreng',
			'Edditional Beef',
			'Edditional Beef',
			'Edditional Ikan',
			'Edditional Ikan',
			'Edditional Ikan',
			'Edditional Ikan',
			'Edditional Udang',
			'Edditional Udang',
			'Edditional Udang',
			'Edditional Udang',
			'Empal penyet',
			'Empal penyet',
			'Empal penyet',
			'Empal penyet',
			'Empal penyet',
			'Empal penyet',
			'Emping',
			'Extra Vaganza Pizza',
			'Extra Vaganza Pizza',
			'Extra Vaganza Pizza',
			'Extra Vaganza Pizza',
			'Extra Vaganza Pizza',
			'Extra Vaganza Pizza',
			'Extra Vaganza Pizza',
			'Extra Vaganza Pizza',
			'Extra Vaganza Pizza',
			'Extra Vaganza Pizza',
			'Extra Vaganza Pizza',
			'Extra Vaganza Pizza',
			'French Friesh',
			'French Friesh',
			'French Friesh',
			'French Friesh',
			'French toast',
			'French toast',
			'French toast',
			'French toast',
			'FUSILI MUSHROOM SAUCE',
			'FUSILI MUSHROOM SAUCE',
			'FUSILI MUSHROOM SAUCE',
			'FUSILI MUSHROOM SAUCE',
			'FUSILI MUSHROOM SAUCE',
			'FUSILI MUSHROOM SAUCE',
			'FUSILI MUSHROOM SAUCE',
			'FUSILI MUSHROOM SAUCE',
			'Gado Gado',
			'Gado Gado',
			'Gado Gado',
			'Gado Gado',
			'Gado Gado',
			'Gado Gado',
			'Gado Gado',
			'Gado Gado',
			'Gado Gado',
			'Gado Gado',
			'Gado Gado',
			'Gado Gado',
			'Gado Gado',
			'Gado Gado',
			'Gado Gado',
			'Gado Gado',
			'Garlic potato',
			'Garlic potato',
			'Garlic potato',
			'Garlic potato',
			'Garlic potato',
			'Garlic potato',
			'Garlic potato',
			'Grill Salmon & Cheese white cream sauce',
			'Grill Salmon & Cheese white cream sauce',
			'Grill Salmon & Cheese white cream sauce',
			'Grill Salmon & Cheese white cream sauce',
			'Grill Salmon & Cheese white cream sauce',
			'Grill Salmon & Cheese white cream sauce',
			'Grill Salmon & Cheese white cream sauce',
			'Grill Salmon & Cheese white cream sauce',
			'Grill Salmon & Cheese white cream sauce',
			'Grill Salmon & Cheese white cream sauce',
			'Grill Salmon & Cheese white cream sauce',
			'Grill Salmon & Cheese white cream sauce',
			'Grill Salmon & Cheese white cream sauce',
			'Grilled Chicken mushroom sauce',
			'Grilled Chicken mushroom sauce',
			'Grilled Chicken mushroom sauce',
			'Grilled Chicken mushroom sauce',
			'Grilled Chicken mushroom sauce',
			'Grilled Chicken mushroom sauce',
			'Grilled Chicken mushroom sauce',
			'Grilled Chicken mushroom sauce',
			'Grilled Chicken mushroom sauce',
			'Grilled Chicken mushroom sauce',
			'Grilled Salmon Cream sauce',
			'Grilled Salmon Cream sauce',
			'Grilled Salmon Cream sauce',
			'Grilled Salmon Cream sauce',
			'Grilled Salmon Cream sauce',
			'Grilled Salmon Cream sauce',
			'Grilled Salmon Cream sauce',
			'Grilled Salmon Cream sauce',
			'Grilled Salmon Cream sauce',
			'Grilled Salmon Cream sauce',
			'Grilled Salmon Cream sauce',
			'Grilled Salmon Cream sauce',
			'Grilled Salmon Teriyaki',
			'Grilled Salmon Teriyaki',
			'Grilled Salmon Teriyaki',
			'Grilled Salmon Teriyaki',
			'Grilled Salmon Teriyaki',
			'Grilled Salmon Teriyaki',
			'Grilled Salmon Teriyaki',
			'Grilled Salmon Teriyaki',
			'Grilled Salmon Teriyaki',
			'Grilled Salmon Teriyaki',
			'Grilled Salmon Teriyaki',
			'Gurami Bakar',
			'Gurami Bakar',
			'Gurami Bakar',
			'Gurami Bakar',
			'Gurami Bakar',
			'Gurami Bakar',
			'Gurami Bakar',
			'Gurami Bakar',
			'Gurami Bakar',
			'Gurami Bakar',
			'Gurami Bakar',
			'Gurami Bakar',
			'Gurami Bakar',
			'Gurami Bakar',
			'Gurami Dabu Dabu',
			'Gurami Dabu Dabu',
			'Gurami Dabu Dabu',
			'Gurami Dabu Dabu',
			'Gurami Dabu Dabu',
			'Gurami Dabu Dabu',
			'Gurami Dabu Dabu',
			'Gurami Dabu Dabu',
			'Gurami penyet',
			'Gurami penyet',
			'Gurami penyet',
			'Gurami penyet',
			'Gurami penyet',
			'Gurami penyet',
			'Gurami penyet',
			'Gurami penyet',
			'Gurami penyet',
			'Gurami penyet',
			'Gurami penyet',
			'Gurami penyet',
			'Gurami penyet',
			'Hot Plate Angsio Tahu Jepang',
			'Hot Plate Angsio Tahu Jepang',
			'Hot Plate Angsio Tahu Jepang',
			'Hot Plate Angsio Tahu Jepang',
			'Hot Plate Angsio Tahu Jepang',
			'Hot Plate Angsio Tahu Jepang',
			'Hot Plate Angsio Tahu Jepang',
			'Hot Plate Angsio Tahu Jepang',
			'Hot Plate Angsio Tahu Jepang',
			'Hot Plate Angsio Tahu Jepang',
			'Hot Plate Angsio Tahu Jepang',
			'Hot Plate Angsio Tahu Jepang',
			'Hot Plate Angsio Tahu Jepang',
			'Hot Plate Tofu szechuan',
			'Hot Plate Tofu szechuan',
			'Hot Plate Tofu szechuan',
			'Hot Plate Tofu szechuan',
			'Hot Plate Tofu szechuan',
			'Hot Plate Tofu szechuan',
			'Hot Plate Tofu szechuan',
			'Hot Plate Tofu szechuan',
			'Hot Plate Tofu szechuan',
			'Hot Plate Tofu szechuan',
			'Hot Plate Tofu szechuan',
			'Ikan gindara Cabe garam',
			'Ikan gindara Cabe garam',
			'Ikan gindara Cabe garam',
			'Ikan gindara Cabe garam',
			'Ikan gindara Cabe garam',
			'Ikan gindara Cabe garam',
			'Ikan gindara Cabe garam',
			'Ikan gindara Cabe garam',
			'Ikan gindara Cabe garam',
			'Ikan gindara Cabe garam',
			'Ikan gindara Cabe garam',
			'Ikan gindara Cabe garam',
			'Ikan gindara Cabe garam',
			'Ikan gindara saus thailand',
			'Ikan gindara saus thailand',
			'Ikan gindara saus thailand',
			'Ikan gindara saus thailand',
			'Ikan gindara saus thailand',
			'Ikan gindara saus thailand',
			'Ikan gindara saus thailand',
			'Ikan gindara saus thailand',
			'Ikan gindara saus thailand',
			'Ikan gindara saus thailand',
			'Ikan gindara saus thailand',
			'Ikan gindara saus thailand',
			'Ikan gindara saus thailand',
			'Ikan gindara Telur asin',
			'Ikan gindara Telur asin',
			'Ikan gindara Telur asin',
			'Ikan gindara Telur asin',
			'Ikan gindara Telur asin',
			'Ikan gindara Telur asin',
			'Ikan gindara Telur asin',
			'Ikan gindara Telur asin',
			'Ikan gindara Telur asin',
			'Ikan gindara Telur asin',
			'Ikan gindara Telur asin',
			'Ikan gindara Telur asin',
			'Jamur tiram cabe garam',
			'Jamur tiram cabe garam',
			'Jamur tiram cabe garam',
			'Jamur tiram cabe garam',
			'Jamur tiram cabe garam',
			'Jamur tiram cabe garam',
			'Japanese Fried Rice',
			'Japanese Fried Rice',
			'Japanese Fried Rice',
			'Japanese Fried Rice',
			'Japanese Fried Rice',
			'Japanese Fried Rice',
			'Japanese Fried Rice',
			'Japanese Fried Rice',
			'Japanese Fried Rice',
			'Japanese Fried Rice',
			'Japanese Fried Rice',
			'Japanese Fried Rice',
			'Japanese Fried Rice',
			'Japanese Fried Rice',
			'Japanese Fried Rice',
			'Japanese Fried Rice',
			'Jumbo Pizza',
			'Jumbo Pizza',
			'Jumbo Pizza',
			'Jumbo Pizza',
			'Jumbo Pizza',
			'Jumbo Pizza',
			'Jumbo Pizza',
			'Jumbo Pizza',
			'Jumbo Pizza',
			'Jumbo Pizza',
			'Jumbo Pizza',
			'Jumbo Pizza',
			'Jumbo Pizza',
			'Jumbo Pizza',
			'Jumbo Pizza',
			'Kakap Dabu dabu',
			'Kakap Dabu dabu',
			'Kakap Dabu dabu',
			'Kakap Dabu dabu',
			'Kakap Dabu dabu',
			'Kakap Dabu dabu',
			'Kakap Dabu dabu',
			'Kakap Dabu dabu',
			'Kepiting soka saus telur asin',
			'Kepiting soka saus telur asin',
			'Kepiting soka saus telur asin',
			'Kepiting soka saus telur asin',
			'Kepiting soka saus telur asin',
			'Kepiting soka saus telur asin',
			'Kepiting soka saus telur asin',
			'Kepiting soka saus telur asin',
			'Kepiting soka saus telur asin',
			'Kothokan ikan kakap',
			'Kothokan ikan kakap',
			'Kothokan ikan kakap',
			'Kothokan ikan kakap',
			'Kothokan ikan kakap',
			'Kothokan ikan kakap',
			'Kothokan ikan kakap',
			'Kothokan ikan kakap',
			'Kothokan ikan kakap',
			'Kothokan ikan kakap',
			'Kothokan ikan kakap',
			'Kothokan ikan kakap',
			'Kothokan ikan kakap',
			'Kothokan ikan kakap',
			'Kothokan ikan kakap',
			'Kothokan ikan kakap',
			'Kothokan ikan kakap',
			'Krupuk udang',
			'Kuah Buntut',
			'Kuah Buntut',
			'Kuah Buntut',
			'Kuah Buntut',
			'Kuah Buntut',
			'Kuah Buntut',
			'Kuah Buntut',
			'Kuah Buntut',
			'Kuah Buntut',
			'Kuah Buntut',
			'Kuah Buntut',
			'Kuah Buntut',
			'Kuah Buntut',
			'Kuah Buntut',
			'Kuah Buntut',
			'Kuah Buntut',
			'Kuah Rawon',
			'Kuah Rawon',
			'Kuah Rawon',
			'Kuah Rawon',
			'Kuah Rawon',
			'Kuah Rawon',
			'Kuah Rawon',
			'Kuah Rawon',
			'Kuah Rawon',
			'Kuah Rawon',
			'Kuah Rawon',
			'Kuah Rawon',
			'Kuah Rawon',
			'Kuah Rawon',
			'Kuah Rawon',
			'Kuah Rawon',
			'Kuah Rawon',
			'Kuah Rawon',
			'Kuah soto ayam',
			'Kuah soto ayam',
			'Kuah soto ayam',
			'Kuah soto ayam',
			'Kuah soto ayam',
			'Kuah soto ayam',
			'Kuah soto ayam',
			'Kuah soto ayam',
			'Kuah soto ayam',
			'Kuah soto ayam',
			'Kuah soto ayam',
			'Kuah soto ayam',
			'Kuah soto ayam',
			'Kuah soto ayam',
			'Kuah telur orak arik',
			'Kuah telur orak arik',
			'Kuah telur orak arik',
			'Kuah telur orak arik',
			'Kuah telur orak arik',
			'Kuah telur orak arik',
			'Kuah telur orak arik',
			'Kuah telur orak arik',
			'Kuah telur orak arik',
			'Kubis',
			'Kwei Tiaw Goreng Ayam',
			'Kwei Tiaw Goreng Ayam',
			'Kwei Tiaw Goreng Ayam',
			'Kwei Tiaw Goreng Ayam',
			'Kwei Tiaw Goreng Ayam',
			'Kwei Tiaw Goreng Ayam',
			'Kwei Tiaw Goreng Ayam',
			'Kwei Tiaw Goreng Ayam',
			'Kwei Tiaw Goreng Ayam',
			'Kwei Tiaw Goreng Ayam',
			'Kwei Tiaw Goreng Ayam',
			'Kwei tiaw Goreng Beef',
			'Kwei tiaw Goreng Beef',
			'Kwei tiaw Goreng Beef',
			'Kwei tiaw Goreng Beef',
			'Kwei tiaw Goreng Beef',
			'Kwei tiaw Goreng Beef',
			'Kwei tiaw Goreng Beef',
			'Kwei tiaw Goreng Beef',
			'Kwei tiaw Goreng Beef',
			'Kwei tiaw Goreng Beef',
			'Kwei tiaw Goreng Beef',
			'Kwei tiaw Goreng Beef',
			'Kwei tiaw Goreng Penang Seafood',
			'Kwei tiaw Goreng Penang Seafood',
			'Kwei tiaw Goreng Penang Seafood',
			'Kwei tiaw Goreng Penang Seafood',
			'Kwei tiaw Goreng Penang Seafood',
			'Kwei tiaw Goreng Penang Seafood',
			'Kwei tiaw Goreng Penang Seafood',
			'Kwei tiaw Goreng Penang Seafood',
			'Kwei tiaw Goreng Penang Seafood',
			'Kwei tiaw Goreng Penang Seafood',
			'Kwei tiaw Goreng Penang Seafood',
			'Kwei tiaw Goreng Penang Seafood',
			'Kwei tiaw Goreng Penang Seafood',
			'Kwei Tiaw Goreng Seafood',
			'Kwei Tiaw Goreng Seafood',
			'Kwei Tiaw Goreng Seafood',
			'Kwei Tiaw Goreng Seafood',
			'Kwei Tiaw Goreng Seafood',
			'Kwei Tiaw Goreng Seafood',
			'Kwei Tiaw Goreng Seafood',
			'Kwei Tiaw Goreng Seafood',
			'Kwei Tiaw Goreng Seafood',
			'Kwei Tiaw Goreng Seafood',
			'Kwei Tiaw Goreng Seafood',
			'Kwei Tiaw Goreng Seafood',
			'Kwei Tiaw Goreng Seafood',
			'Kwei tiaw Hot Plate Ayam',
			'Kwei tiaw Hot Plate Ayam',
			'Kwei tiaw Hot Plate Ayam',
			'Kwei tiaw Hot Plate Ayam',
			'Kwei tiaw Hot Plate Ayam',
			'Kwei tiaw Hot Plate Ayam',
			'Kwei tiaw Hot Plate Ayam',
			'Kwei tiaw Hot Plate Ayam',
			'Kwei tiaw Hot Plate Ayam',
			'Kwei tiaw Hot Plate Ayam',
			'Kwei tiaw Hot Plate Ayam',
			'Kwei tiaw Hot Plate Ayam',
			'Kwei tiaw Hot Plate Ayam',
			'Kwei Tiaw Hot Plate Beef',
			'Kwei Tiaw Hot Plate Beef',
			'Kwei Tiaw Hot Plate Beef',
			'Kwei Tiaw Hot Plate Beef',
			'Kwei Tiaw Hot Plate Beef',
			'Kwei Tiaw Hot Plate Beef',
			'Kwei Tiaw Hot Plate Beef',
			'Kwei Tiaw Hot Plate Beef',
			'Kwei Tiaw Hot Plate Beef',
			'Kwei Tiaw Hot Plate Beef',
			'Kwei Tiaw Hot Plate Beef',
			'Kwei Tiaw Hot Plate Beef',
			'Kwei Tiaw Hot Plate Beef',
			'Kwei Tiaw Hot Plate Seafood',
			'Kwei Tiaw Hot Plate Seafood',
			'Kwei Tiaw Hot Plate Seafood',
			'Kwei Tiaw Hot Plate Seafood',
			'Kwei Tiaw Hot Plate Seafood',
			'Kwei Tiaw Hot Plate Seafood',
			'Kwei Tiaw Hot Plate Seafood',
			'Kwei Tiaw Hot Plate Seafood',
			'Kwei Tiaw Hot Plate Seafood',
			'Kwei Tiaw Hot Plate Seafood',
			'Kwei Tiaw Hot Plate Seafood',
			'Kwei Tiaw Hot Plate Seafood',
			'Kwei Tiaw Hot Plate Seafood',
			'Kwei Tiaw Hot Plate Seafood',
			'Lalapan',
			'Lalapan',
			'Lalapan',
			'Lalapan',
			'Lalapan',
			'Lontong Kikil',
			'Lontong Kikil',
			'Lontong Kikil',
			'Lontong Kikil',
			'Lontong Kikil',
			'Lontong Kikil',
			'Lontong Kikil',
			'Lontong Kikil',
			'Lontong Kikil',
			'Lontong Kikil',
			'Lontong Kikil',
			'Lontong Kikil',
			'Lontong Kikil',
			'Lontong Kikil',
			'Lontong Kikil',
			'Lumpia Goreng',
			'Lumpia Goreng',
			'Lumpia Goreng',
			'Lumpia Goreng',
			'Lumpia Goreng',
			'Lumpia Goreng',
			'Lumpia Goreng',
			'Lumpia Goreng',
			'Lumpia Goreng',
			'Lumpia Goreng',
			'Lumpia Goreng',
			'Lumpia Goreng',
			'Lumpia Kucai',
			'Lumpia Kucai',
			'Lumpia Kucai',
			'Lumpia Kucai',
			'Lumpia Kucai',
			'Lumpia Kucai',
			'Lumpia Semarang',
			'Martabak daging sapi',
			'Martabak daging sapi',
			'Martabak daging sapi',
			'Martabak daging sapi',
			'Martabak daging sapi',
			'Martabak daging sapi',
			'Martabak daging sapi',
			'Martabak daging sapi',
			'Martabak daging sapi',
			'Martabak daging sapi',
			'Mie Goreng Ayam',
			'Mie Goreng Ayam',
			'Mie Goreng Ayam',
			'Mie Goreng Ayam',
			'Mie Goreng Ayam',
			'Mie Goreng Ayam',
			'Mie Goreng Ayam',
			'Mie Goreng Ayam',
			'Mie Goreng Ayam',
			'Mie Goreng Ayam',
			'Mie Goreng Ayam',
			'Mie Goreng Ayam',
			'Mie Goreng Ayam',
			'Mie Goreng Ayam',
			'Mie Goreng Ayam',
			'Mie Goreng Beef',
			'Mie Goreng Beef',
			'Mie Goreng Beef',
			'Mie Goreng Beef',
			'Mie Goreng Beef',
			'Mie Goreng Beef',
			'Mie Goreng Beef',
			'Mie Goreng Beef',
			'Mie Goreng Beef',
			'Mie Goreng Beef',
			'Mie Goreng Beef',
			'Mie Goreng Beef',
			'Mie Goreng Beef',
			'Mie Goreng Beef',
			'Mie Goreng Beef',
			'Mie Goreng Jawa',
			'Mie Goreng Jawa',
			'Mie Goreng Jawa',
			'Mie Goreng Jawa',
			'Mie Goreng Jawa',
			'Mie Goreng Jawa',
			'Mie Goreng Jawa',
			'Mie Goreng Jawa',
			'Mie Goreng Jawa',
			'Mie Goreng Jawa',
			'Mie Goreng Seafood',
			'Mie Goreng Seafood',
			'Mie Goreng Seafood',
			'Mie Goreng Seafood',
			'Mie Goreng Seafood',
			'Mie Goreng Seafood',
			'Mie Goreng Seafood',
			'Mie Goreng Seafood',
			'Mie Goreng Seafood',
			'Mie Goreng Seafood',
			'Mie Goreng Seafood',
			'Mie Goreng Seafood',
			'Mie Goreng Seafood',
			'Mie Goreng Seafood',
			'Mie Goreng Seafood',
			'Mie Goreng Seafood',
			'Mie Goreng Seafood',
			'Mie Hot Plate ayam',
			'Mie Hot Plate ayam',
			'Mie Hot Plate ayam',
			'Mie Hot Plate ayam',
			'Mie Hot Plate ayam',
			'Mie Hot Plate ayam',
			'Mie Hot Plate ayam',
			'Mie Hot Plate ayam',
			'Mie Hot Plate ayam',
			'Mie Hot Plate ayam',
			'Mie Hot Plate ayam',
			'Mie Hot Plate ayam',
			'Mie Hot Plate ayam',
			'Mie Hot Plate ayam',
			'Mie Hot Plate daging sapi',
			'Mie Hot Plate daging sapi',
			'Mie Hot Plate daging sapi',
			'Mie Hot Plate daging sapi',
			'Mie Hot Plate daging sapi',
			'Mie Hot Plate daging sapi',
			'Mie Hot Plate daging sapi',
			'Mie Hot Plate daging sapi',
			'Mie Hot Plate daging sapi',
			'Mie Hot Plate daging sapi',
			'Mie Hot Plate daging sapi',
			'Mie Hot Plate daging sapi',
			'Mie Hot Plate daging sapi',
			'Mie Hot Plate daging sapi',
			'Mie Hot Plate daging sapi',
			'Mie Hot Plate seafood',
			'Mie Hot Plate seafood',
			'Mie Hot Plate seafood',
			'Mie Hot Plate seafood',
			'Mie Hot Plate seafood',
			'Mie Hot Plate seafood',
			'Mie Hot Plate seafood',
			'Mie Hot Plate seafood',
			'Mie Hot Plate seafood',
			'Mie Hot Plate seafood',
			'Mie Hot Plate seafood',
			'Mie Hot Plate seafood',
			'Mie Hot Plate seafood',
			'Mie Hot Plate seafood',
			'Mie Hot Plate seafood',
			'Mie Hot Plate seafood',
			'Mie Kocok Medan',
			'Mie Kocok Medan',
			'Mie Kocok Medan',
			'Mie Kocok Medan',
			'Mie Kocok Medan',
			'Mie Kocok Medan',
			'Mie Kocok Medan',
			'Mie Kocok Medan',
			'Mini Spring Roll',
			'Mini Spring Roll',
			'Mini Spring Roll',
			'Mini Spring Roll',
			'Misoa goreng seafood',
			'Misoa goreng seafood',
			'Misoa goreng seafood',
			'Misoa goreng seafood',
			'Misoa goreng seafood',
			'Misoa goreng seafood',
			'Misoa goreng seafood',
			'Misoa goreng seafood',
			'Misoa goreng seafood',
			'Misoa goreng seafood',
			'Misoa goreng seafood',
			'Misoa goreng seafood',
			'Misoa goreng seafood',
			'Misoa goreng seafood',
			'Misoa goreng seafood',
			'Nasi Bebek Graha',
			'Nasi Bebek Graha',
			'Nasi Bebek Graha',
			'Nasi Bebek Graha',
			'Nasi Bebek Graha',
			'Nasi Bebek Graha',
			'Nasi Cap Cay',
			'Nasi Cap Cay',
			'Nasi Cap Cay',
			'Nasi Cap Cay',
			'Nasi Cap Cay',
			'Nasi Cap Cay',
			'Nasi Cap Cay',
			'Nasi Cap Cay',
			'Nasi Cap Cay',
			'Nasi Cap Cay',
			'Nasi Cap Cay',
			'Nasi Cap Cay',
			'Nasi Cap Cay',
			'Nasi Cap Cay',
			'Nasi Cap Cay',
			'Nasi Cap Cay',
			'Nasi Cap Cay',
			'Nasi Cap Cay',
			'Nasi Cap Cay',
			'Nasi Goreng Cabe Kering',
			'Nasi Goreng Cabe Kering',
			'Nasi Goreng Cabe Kering',
			'Nasi Goreng Cabe Kering',
			'Nasi Goreng Cabe Kering',
			'Nasi Goreng Cabe Kering',
			'Nasi Goreng Cabe Kering',
			'Nasi Goreng Cabe Kering',
			'Nasi Goreng Cabe Kering',
			'Nasi Goreng Cabe Kering',
			'Nasi Goreng Cabe Kering',
			'Nasi goreng hokkian',
			'Nasi goreng hokkian',
			'Nasi goreng hokkian',
			'Nasi goreng hokkian',
			'Nasi goreng hokkian',
			'Nasi goreng hokkian',
			'Nasi goreng hokkian',
			'Nasi goreng hokkian',
			'Nasi goreng hokkian',
			'Nasi goreng hokkian',
			'Nasi goreng hokkian',
			'Nasi goreng hokkian',
			'Nasi goreng hokkian',
			'Nasi goreng hokkian',
			'Nasi goreng hokkian',
			'Nasi goreng hokkian',
			'Nasi Goreng Jawa',
			'Nasi Goreng Jawa',
			'Nasi Goreng Jawa',
			'Nasi Goreng Jawa',
			'Nasi Goreng Jawa',
			'Nasi Goreng Jawa',
			'Nasi Goreng Jawa',
			'Nasi Goreng Jawa',
			'Nasi Goreng Jawa',
			'Nasi Goreng Jawa',
			'Nasi Goreng Salmon',
			'Nasi Goreng Salmon',
			'Nasi Goreng Salmon',
			'Nasi Goreng Salmon',
			'Nasi Goreng Salmon',
			'Nasi Goreng Salmon',
			'Nasi Goreng Salmon',
			'Nasi Goreng Salmon',
			'Nasi Goreng Salmon',
			'Nasi Goreng Salmon',
			'Nasi Goreng Salmon',
			'Nasi Goreng Salmon',
			'Nasi Goreng Salmon',
			'Nasi Goreng Salmon',
			'Nasi Goreng Salmon',
			'Nasi goreng Seafood',
			'Nasi goreng Seafood',
			'Nasi goreng Seafood',
			'Nasi goreng Seafood',
			'Nasi goreng Seafood',
			'Nasi goreng Seafood',
			'Nasi goreng Seafood',
			'Nasi goreng Seafood',
			'Nasi goreng Seafood',
			'Nasi goreng Seafood',
			'Nasi goreng Seafood',
			'Nasi goreng Seafood',
			'Nasi goreng Seafood',
			'Nasi goreng Seafood',
			'Nasi goreng Seafood',
			'Nasi goreng Seafood',
			'Nasi goreng Seafood',
			'Nasi Goreng Spesial',
			'Nasi Goreng Spesial',
			'Nasi Goreng Spesial',
			'Nasi Goreng Spesial',
			'Nasi Goreng Spesial',
			'Nasi Goreng Spesial',
			'Nasi Goreng Spesial',
			'Nasi Goreng Spesial',
			'Nasi Goreng Spesial',
			'Nasi Goreng Spesial',
			'Nasi Goreng Spesial',
			'Nasi Goreng Spesial',
			'Nasi Goreng Spesial',
			'Nasi Goreng Spesial',
			'Nasi Goreng Spesial',
			'Nasi Goreng X.O',
			'Nasi Goreng X.O',
			'Nasi Goreng X.O',
			'Nasi Goreng X.O',
			'Nasi Goreng X.O',
			'Nasi Goreng X.O',
			'Nasi Goreng X.O',
			'Nasi Goreng X.O',
			'Nasi Goreng X.O',
			'Nasi Goreng X.O',
			'Nasi Goreng X.O',
			'Nasi Goreng X.O',
			'Nasi Goreng X.O',
			'Nasi Goreng X.O',
			'Nasi Pecel Madiun',
			'Nasi Pecel Madiun',
			'Nasi Pecel Madiun',
			'Nasi Pecel Madiun',
			'Nasi Pecel Madiun',
			'Nasi Pecel Madiun',
			'Nasi Pecel Madiun',
			'Nasi Pecel Madiun',
			'Nasi Pecel Madiun',
			'Nasi Pecel Madiun',
			'Nasi Putih',
			'Paket bakso 5 pcs (Shelter)',
			'Paket bakso 5 pcs (Shelter)',
			'Paket bakso 5 pcs (Shelter)',
			'Paket bakso 5 pcs (Shelter)',
			'Paket bakso 5 pcs (Shelter)',
			'Paket bakso 5 pcs (Shelter)',
			'Paket bakso 5 pcs (Shelter)',
			'Pangsit Goreng',
			'Pangsit Goreng',
			'Pangsit Goreng',
			'Pangsit Goreng',
			'Pangsit Goreng',
			'Pangsit Goreng',
			'Pangsit Goreng',
			'Pangsit Goreng',
			'Pangsit Goreng',
			'Pangsit Goreng',
			'Pangsit Goreng',
			'Pangsit Mie Ayam/Jamur',
			'Pangsit Mie Ayam/Jamur',
			'Pangsit Mie Ayam/Jamur',
			'Pangsit Mie Ayam/Jamur',
			'Pangsit Mie Ayam/Jamur',
			'Pangsit Mie Ayam/Jamur',
			'Pangsit Mie Ayam/Jamur',
			'Pangsit Mie Ayam/Jamur',
			'Pangsit Mie Ayam/Jamur',
			'Pangsit Mie Ayam/Jamur',
			'Pangsit Mie Ayam/Jamur',
			'Pangsit Mie Ayam/Jamur',
			'Pisang goreng keju',
			'Pisang goreng keju',
			'Pisang goreng keju',
			'Pisang goreng keju',
			'Pisang Rebus',
			'Rawon Iga Sapi',
			'Rawon Iga Sapi',
			'Rawon Iga Sapi',
			'Rawon Iga Sapi',
			'Rawon Iga Sapi',
			'Rawon Iga Sapi',
			'Rawon Iga Sapi',
			'Rawon Iga Sapi',
			'Rawon Iga Sapi',
			'Rawon Iga Sapi',
			'Rempeyek',
			'Rempeyek',
			'Rempeyek',
			'Rempeyek',
			'Rempeyek',
			'Rempeyek',
			'Salmon dabu dabu',
			'Salmon dabu dabu',
			'Salmon dabu dabu',
			'Salmon dabu dabu',
			'Salmon dabu dabu',
			'Salmon dabu dabu',
			'Salmon dabu dabu',
			'Salmon dabu dabu',
			'Salmon Fettucini',
			'Salmon Fettucini',
			'Salmon Fettucini',
			'Salmon Fettucini',
			'Salmon Fettucini',
			'Salmon Fettucini',
			'Salmon Fettucini',
			'Salmon Fettucini',
			'Salmon Fettucini',
			'Salmon Fettucini',
			'Sambal bajak',
			'Sambal bajak',
			'Sambal bajak',
			'Sambal bajak',
			'Sambal bajak',
			'Sambal bajak',
			'Sambal bajak',
			'Sambal bajak',
			'Sambal bajak',
			'Sambal dabu-dabu',
			'Sambal dabu-dabu',
			'Sambal dabu-dabu',
			'Sambal dabu-dabu',
			'Sambal dabu-dabu',
			'Sambal dabu-dabu',
			'Sambal dabu-dabu',
			'Sambal dabu-dabu',
			'Sambal dabu-dabu',
			'Sambal dabu-dabu',
			'Sate Ayam',
			'Sate Ayam',
			'Sate Ayam',
			'Sate Ayam',
			'Sate Ayam',
			'Sate Ayam',
			'Sate Ayam',
			'Siomay Bandung',
			'Siomay Bandung',
			'Siomay Bandung',
			'Siomay Bandung',
			'Siomay Bandung',
			'Siomay Bandung',
			'Siomay Bandung',
			'Siomay Bandung',
			'Siomay(Shelter)',
			'Somen dingin',
			'Somen dingin',
			'Somen dingin',
			'Somen dingin',
			'Somen dingin',
			'Somen dingin',
			'Soto ayam',
			'Soto ayam',
			'Soto ayam',
			'Soto ayam',
			'Soto ayam',
			'Soto ayam',
			'Soto ayam',
			'Soto ayam',
			'Soto ayam',
			'Soto ayam',
			'Soto ayam',
			'Soto ayam',
			'Soto ayam',
			'Soto ayam',
			'Soto Daging',
			'Soto Daging',
			'Soto Daging',
			'Soto Daging',
			'Soto Daging',
			'Soto Daging',
			'Soto Daging',
			'Soto Daging',
			'Soto Daging',
			'Soto Daging',
			'Soto Daging',
			'Soto tangkar',
			'Soto tangkar',
			'Soto tangkar',
			'Soto tangkar',
			'Soto tangkar',
			'Soto tangkar',
			'Soto tangkar',
			'Soto tangkar',
			'Soto tangkar',
			'Soto tangkar',
			'Soto tangkar',
			'Soto tangkar',
			'Soto tangkar',
			'Soto tangkar',
			'Soto tangkar',
			'Soto tangkar',
			'Soup ikan salmon',
			'Soup ikan salmon',
			'Soup ikan salmon',
			'Soup ikan salmon',
			'Soup ikan salmon',
			'Soup ikan salmon',
			'Soup ikan salmon',
			'Soup ikan salmon',
			'Soup ikan salmon',
			'Soup ikan salmon',
			'Soup ikan salmon',
			'Soup ikan salmon',
			'Soup ikan salmon',
			'Soup ikan salmon',
			'Soup ikan salmon',
			'Soup ikan salmon',
			'Soup ikan salmon',
			'Soup ikan salmon',
			'Soup ikan salmon',
			'Soup kapala ikan',
			'Soup kapala ikan',
			'Soup kapala ikan',
			'Soup kapala ikan',
			'Soup kapala ikan',
			'Soup kapala ikan',
			'Soup kapala ikan',
			'Soup kapala ikan',
			'Soup kapala ikan',
			'Soup kapala ikan',
			'Soup kapala ikan',
			'Soup kapala ikan',
			'Soup kapala ikan',
			'Soup kapala ikan',
			'Soup kapala ikan',
			'Soup kapala ikan',
			'Soup kapala ikan',
			'Soup kapala ikan',
			'Sup Buntut Bakar',
			'Sup Buntut Bakar',
			'Sup Buntut Bakar',
			'Sup Buntut Bakar',
			'Sup Buntut Bakar',
			'Sup Buntut Bakar',
			'Sup Buntut Bakar',
			'Sup Buntut Bakar',
			'Sup Buntut Bakar',
			'Sup Buntut Bakar',
			'Sup Buntut Bakar',
			'Sup Buntut Bakar',
			'Sup Buntut Bakar',
			'Sup Buntut Bakar',
			'Sup Buntut Bakar',
			'Sup Buntut Bakar',
			'Sup buntut goreng',
			'Sup buntut goreng',
			'Sup buntut goreng',
			'Sup buntut goreng',
			'Sup buntut goreng',
			'Sup buntut goreng',
			'Sup buntut goreng',
			'Sup buntut goreng',
			'Sup buntut goreng',
			'Sup buntut goreng',
			'Sup buntut goreng',
			'Sup buntut goreng',
			'Sup buntut goreng',
			'Sup buntut goreng',
			'Sup buntut goreng',
			'Sup buntut goreng',
			'Sup buntut goreng',
			'Sup Buntut kuah',
			'Sup Buntut kuah',
			'Sup Buntut kuah',
			'Sup Buntut kuah',
			'Sup Buntut kuah',
			'Sup Buntut kuah',
			'Sup Buntut kuah',
			'Sup Buntut kuah',
			'Sup Buntut kuah',
			'Sup Buntut kuah',
			'Sup Buntut kuah',
			'Sup Buntut kuah',
			'Sup Buntut kuah',
			'Sup Buntut kuah',
			'Sup Gurami Sayur Asin',
			'Sup Gurami Sayur Asin',
			'Sup Gurami Sayur Asin',
			'Sup Gurami Sayur Asin',
			'Sup Gurami Sayur Asin',
			'Sup Gurami Sayur Asin',
			'Sup Gurami Sayur Asin',
			'Sup Gurami Sayur Asin',
			'Sup Gurami Sayur Asin',
			'Sup Gurami Sayur Asin',
			'Sup Gurami Sayur Asin',
			'Sup Gurami Sayur Asin',
			'Sup Gurami Sayur Asin',
			'Sup Gurami Sayur Asin',
			'Sup Gurami Sayur Asin',
			'Sup iga Bakar',
			'Sup iga Bakar',
			'Sup iga Bakar',
			'Sup iga Bakar',
			'Sup iga Bakar',
			'Sup iga Bakar',
			'Sup iga Bakar',
			'Sup iga Bakar',
			'Sup iga Bakar',
			'Sup iga Bakar',
			'Sup iga Bakar',
			'Sup iga Bakar',
			'Sup iga Bakar',
			'Sup iga Bakar',
			'Sup iga sapi goreng',
			'Sup iga sapi goreng',
			'Sup iga sapi goreng',
			'Sup iga sapi goreng',
			'Sup iga sapi goreng',
			'Sup iga sapi goreng',
			'Sup iga sapi goreng',
			'Sup iga sapi goreng',
			'Sup iga sapi goreng',
			'Sup iga sapi goreng',
			'Sup iga sapi goreng',
			'Sup iga sapi goreng',
			'Sup iga sapi goreng',
			'Sup iga sapi goreng',
			'Sup iga sapi goreng',
			'Sup iga sapi goreng',
			'Sup iga sapi kuah',
			'Sup iga sapi kuah',
			'Sup iga sapi kuah',
			'Sup iga sapi kuah',
			'Sup iga sapi kuah',
			'Sup iga sapi kuah',
			'Sup iga sapi kuah',
			'Sup iga sapi kuah',
			'Sup iga sapi kuah',
			'Sup iga sapi kuah',
			'Sup iga sapi kuah',
			'Sup Sehat',
			'Sup Sehat',
			'Sup Sehat',
			'Sup Sehat',
			'Sup Sehat',
			'Sup Sehat',
			'Sup Sehat',
			'Sup Sehat',
			'Sup Sehat',
			'Sup Sehat',
			'Sup Sehat',
			'Sup Sehat',
			'Sup Sehat',
			'Sup Sehat',
			'Sup Sehat',
			'Sup Sehat',
			'Sup Sehat',
			'Sup Sehat',
			'Tahu Cabe Garam',
			'Tahu Cabe Garam',
			'Tahu Cabe Garam',
			'Tahu Cabe Garam',
			'Tahu Cabe Garam',
			'Tahu Cabe Garam',
			'Tahu Cabe Garam',
			'Tahu Cabe Garam',
			'Tahu Crispy',
			'Tahu Crispy',
			'Tahu Crispy',
			'Tahu Crispy',
			'Tahu Goreng',
			'Tahu Goreng',
			'Tahu Goreng',
			'Tahu Goreng',
			'Tahu Goreng',
			'Tahu isi Ayam Jamur',
			'Tahu isi Ayam Jamur',
			'Tahu isi Ayam Jamur',
			'Tahu isi Ayam Jamur',
			'Tahu isi Ayam Jamur',
			'Tahu isi Ayam Jamur',
			'Tahu isi Ayam Jamur',
			'Tahu isi Ayam Jamur',
			'Tahu isi Ayam Jamur',
			'Tahu isi Ayam Jamur',
			'Tahu isi Ayam Jamur',
			'Tahu isi Ayam Jamur',
			'Tahu isi Ayam Jamur',
			'Tahu Pong',
			'Tahu Pong',
			'Tahu Pong',
			'Tahu Pong',
			'Tahu Pong',
			'Telur, Tempe & Telur Penyet',
			'Telur, Tempe & Telur Penyet',
			'Telur, Tempe & Telur Penyet',
			'Telur, Tempe & Telur Penyet',
			'Telur, Tempe & Telur Penyet',
			'Telur, Tempe & Telur Penyet',
			'Telur, Tempe & Telur Penyet',
			'Telur, Tempe & Telur Penyet',
			'Telur, Tempe & Telur Penyet',
			'Tempe Goreng',
			'Tempe Goreng',
			'Tempe Goreng',
			'Tempe Goreng',
			'Tempe Goreng',
			'Tumis tauge ikan asin',
			'Tumis tauge ikan asin',
			'Tumis tauge ikan asin',
			'Tumis tauge ikan asin',
			'Tumis tauge ikan asin',
			'Tumis tauge ikan asin',
			'Tumis tauge ikan asin',
			'Tumis tauge ikan asin',
			'Tumis tauge ikan asin',
			'Tumis tauge ikan asin',
			'Tumis tauge ikan asin',
			'Tumis tauge ikan asin',
			'Saus Thailand',
			'Saus Thailand',
			'Saus Thailand',
			'Saus Thailand',
			'Saus Thailand',
			'Saus Thailand',
			'Saus Thailand',
			'Saus Thailand',
			'Saus Thailand',
			'Saus Thailand',
			'Saus Thailand',
			'Saus Teriyaki',
			'Saus Teriyaki',
			'Saus Teriyaki',
			'Saus Teriyaki',
			'Saus Teriyaki',
			'Saus Teriyaki',
			'Saus Teriyaki',
			'Saus Teriyaki',
			'Saus Teriyaki',
			'Saus Teriyaki',
			'Saus Teriyaki',
			'Tepung Campur',
			'Tepung Campur',
			'Tepung Campur',
			'Tepung Campur',
			'Tepung Campur',
			'Tepung Campur',
			'Tepung Campur',
			'Bakso',
			'Bakso',
			'Bakso',
			'Bakso',
			'Bakso',
			'Bakso',
			'Bakso',
			'Bakso',
			'Siomay',
			'Siomay',
			'Siomay',
			'Siomay',
			'Siomay',
			'Siomay',
			'Siomay',
			'Siomay',
			'Siomay',
			'Tahu bakso',
			'Tahu bakso',
			'Tahu bakso',
			'Tahu bakso',
			'Tahu bakso',
			'Tahu bakso',
			'Tahu bakso',
			'Tahu bakso',
			'Tahu bakso',
			'Saus Mushroom',
			'Saus Mushroom',
			'Saus Mushroom',
			'Saus Mushroom',
			'Saus Mushroom',
			'Saus Mushroom',
			'Saus Mushroom',
			'Saus Mushroom',
			'Saus Mushroom',
			'Saus Mushroom',
			'Saus Mushroom',
			'Saus Mushroom',
			'Saus Mushroom',
			'Saus mie',
			'Saus mie',
			'Saus mie',
			'Saus mie',
			'Saus mie',
			'Saus mie',
			'Saus mie',
			'Acar',
			'Acar',
			'Acar',
			'Acar',
			'Acar',
			'Sambel soto',
			'Sambel soto',
			'Sambel soto',
			'Sambel bajak',
			'Sambel bajak',
			'Sambel bajak',
			'Sambel bajak',
			'Sambel bajak',
			'Sambel bajak',
			'Sambel bajak',
			'Sambel bajak',
			'Sambel bajak',
			'Bumbu Siomay',
			'Bumbu Siomay',
			'Bumbu Siomay',
			'Bumbu Siomay',
			'Bumbu Siomay',
			'Bumbu Siomay',
			'Bumbu Siomay',
			'Bumbu Siomay',
			'Bumbu Siomay',
			'Bumbu xo',
			'Bumbu xo',
			'Bumbu xo',
			'Bumbu xo',
			'Bumbu xo',
			'Bumbu xo',
			'Bumbu xo',
			'Bumbu xo',
			'Bumbu xo',
			'Bumbu xo',
			'Sambel dabu dabu',
			'Sambel dabu dabu',
			'Sambel dabu dabu',
			'Sambel dabu dabu',
			'Sambel dabu dabu',
			'Sambel dabu dabu',
			'Sambal hongkong',
			'Sambal hongkong',
			'Sambal hongkong',
			'Sambal hongkong',
			'Sambal hongkong',
			'Sambal hongkong',
			'Sambal hongkong',
			'Sambal hongkong',
			'Sambal hongkong',
			'Sambal hongkong',
			'Saus cah',
			'Saus cah',
			'Saus cah',
			'Saus cah',
			'Saus cah',
			'Saus cah',
			'Saus cah',
			'Saus cah',
			'Saus black papper',
			'Saus black papper',
			'Saus black papper',
			'Saus black papper',
			'Saus black papper',
			'Saus black papper',
			'Saus black papper',
			'Saus kanton',
			'Saus kanton',
			'Saus kanton',
			'Saus kanton',
			'Saus kanton',
			'Saus Beajing',
			'Saus Beajing',
			'Saus Beajing',
			'Saus Beajing',
			'Saus Beajing',
			'Saus Beajing',
			'Saus cabe kering',
			'Saus cabe kering',
			'Saus cabe kering',
			'Saus cabe kering',
			'Saus cabe kering',
			'Saus cabe kering',
			'Saus cabe kering',
			'Saus Jahe',
			'Saus Jahe',
			'Saus Jahe',
			'Saus Jahe',
			'Saus Jahe',
			'Saus Jahe',
			'Saus Jahe',
			'Saus Jahe',
			'Saus Rempah',
			'Saus Rempah',
			'Saus Rempah',
			'Saus Rempah',
			'Saus Rempah',
			'Saus Rempah',
			'Saus Rempah',
			'Saus Rempah',
			'Saus Rempah',
			'Saus Rempah',
			'Saus Rempah',
			'Saus Rempah',
			'Saus Rempah',
			'Tepung tahu isi',
			'Tepung tahu isi',
			'Tepung tahu isi',
			'Tepung tahu isi',
			'Tepung tahu isi',
			'Tepung tahu isi',
			'Tepung tahu isi',
			'Tepung tahu isi',
			'Saus Teluk',
			'Saus Teluk',
			'Saus Teluk',
			'Saus Teluk',
			'Saus Teluk',
			'Saus Teluk',
			'Saus Teluk',
			'Saus Teluk',
			'Saus Teluk',
			'Bumbu Wayin',
			'Bumbu Wayin',
			'Bumbu Wayin',
			'Bumbu Wayin',
			'Bumbu Wayin',
			'Bumbu Wayin',
			'Bumbu Wayin',
			'Bumbu Wayin',
			'Bumbu rica-rica',
			'Bumbu rica-rica',
			'Bumbu rica-rica',
			'Bumbu rica-rica',
			'Bumbu rica-rica',
			'Bumbu rica-rica',
			'Bumbu rica-rica',
			'Bumbu rica-rica',
			'Bumbu rica-rica',
			'Bumbu rica-rica',
			'Bumbu rica-rica',
			'Bumbu rica-rica',
			'Bumbu rica-rica',
			'Kuah Somen',
			'Kuah Somen',
			'Kuah Somen',
			'Kuah Somen',
			'Kuah Rawon',
			'Kuah Rawon',
			'Kuah Rawon',
			'Kuah Rawon',
			'Kuah Rawon',
			'Kuah Rawon',
			'Kuah Rawon',
			'Kuah Rawon',
			'Kuah Rawon',
			'Kuah Rawon',
			'Kuah Rawon',
			'Kuah Rawon',
			'Kuah soto ayam',
			'Kuah soto ayam',
			'Kuah soto ayam',
			'Kuah soto ayam',
			'Kuah soto ayam',
			'Kuah soto ayam',
			'Kuah soto ayam',
			'Kuah soto ayam',
			'Kuah soto ayam',
			'Kuah soto ayam',
			'Kuah soto ayam',
			'Kuah soto ayam',
			'Bumbu Kuning',
			'Bumbu Kuning',
			'Bumbu Kuning',
			'Bumbu Kuning',
			'Bumbu Kuning',
			'Bumbu Kuning',
			'Kuah telor orak arik',
			'Kuah telor orak arik',
			'Kuah telor orak arik',
			'Kuah telor orak arik',
			'Kuah telor orak arik',
			'Kuah telor orak arik',
			'Kuah telor orak arik',
			'Kuah telor orak arik',
			'Kuah telor orak arik',
			'Kuah Buntut',
			'Kuah Buntut',
			'Kuah Buntut',
			'Kuah Buntut',
			'Kuah Buntut',
			'Kuah Buntut',
			'Kuah Buntut',
			'Kuah Buntut',
			'Kuah Buntut',
			'Kuah Buntut',
			'Tomato Concase',
			'Tomato Concase',
			'Tomato Concase',
			'Tomato Concase',
			'Tomato Concase',
			'Tomato Concase',
			'Tomato Concase',
			'Tomato Concase',
			'Tomato Concase',
			'Tomato Concase',
			'Mashroom saus',
			'Mashroom saus',
			'Mashroom saus',
			'Mashroom saus',
			'Mashroom saus',
			'Mashroom saus',
			'Mashroom saus',
			'Mashroom saus',
			'Mashroom saus',
			'Mashroom saus',
			'Mashroom saus',
			'Gravy sauce',
			'Gravy sauce',
			'Gravy sauce',
			'Gravy sauce',
			'Gravy sauce',
			'Gravy sauce',
			'Gravy sauce',
			'Gravy sauce',
			'Gravy sauce',
			'Gravy sauce',
			'Gravy sauce',
			'Rosemary sauce',
			'Rosemary sauce',
			'Rosemary sauce',
			'Rosemary sauce',
			'Rosemary sauce',
			'Rosemary sauce',
			'Rosemary sauce',
			'Rosemary sauce',
			'Rosemary sauce',
			'Rosemary sauce',
			'Rosemary sauce',
			'Dough pizza',
			'Dough pizza',
			'Dough pizza',
			'Dough pizza',
			'Dough pizza',
			'Dough pizza',
			'Dough pizza',
			'Dough pizza',
			'Roti tawar',
			'Roti tawar',
			'Roti tawar',
			'Roti tawar',
			'Roti tawar',
			'Roti tawar',
			'Roti tawar',
			'Roti tawar',
			'Tar - tar saus',
			'Tar - tar saus',
			'Tar - tar saus',
			'Tar - tar saus',
			'Tar - tar saus',
			'Tar - tar saus',
			'Sambal balado',
			'Sambal balado',
			'Sambal balado',
			'Sambal balado',
			'Sambal balado',
			'Sambal balado',
			'bumbu taliwang',
			'bumbu taliwang',
			'bumbu taliwang',
			'bumbu taliwang',
			'bumbu taliwang',
			'bumbu taliwang',
			'bumbu taliwang',
			'Bumbu Sate',
			'Bumbu Sate',
			'Bumbu Sate',
			'Bumbu Sate',
			'Saus Aroma',
			'Saus Aroma',
			'Saus Aroma',
			'Saus Aroma',
			'Saus Aroma',
			'Saus Aroma',
			'Saus Aroma',
			'Saus Aroma',
			'Saus Aroma',
			'Saus Aroma',
			'Saus Aroma',
			'Saus Aroma',
			'Saus Aroma',
			'Tahu Bakso Buat',
			'Tahu Bakso Buat',
			'Pangsit Goreng',
			'Pangsit Goreng',
			'Adonan lumpia kucai',
			'Adonan lumpia kucai',
			'Adonan lumpia kucai',
			'Adonan lumpia kucai',
			'Adonan lumpia kucai',
			'Adonan lumpia kucai',
			'Adonan lumpia kucai',
			'Adonan lumpia kucai',
			'Adonan lumpia kucai',
			'Adonan lumpia kucai',
			'Adonan lumpia kucai',
			'Adonan Udang',
			'Adonan Udang',
			'Adonan Udang',
			'Adonan Udang',
			'Adonan Udang',
			'Adonan Udang',
			'Adonan Udang',
			'Adonan Udang',
			'Adonan Udang',
			'Saus Asam manis',
			'Saus Asam manis',
			'Saus Asam manis',
			'Saus Asam manis',
			'Saus Asam manis',
			'Saus Asam manis',
			'Saus Asam manis',
			'Saus Asam manis',
			'Saus Asam manis',
			'Saus Asam manis',
			'Saus Asam manis',
			'Kuah soto medan',
			'Kuah soto medan',
			'Kuah soto medan',
			'Kuah soto medan',
			'Kuah soto medan',
			'Kuah soto medan',
			'Kuah soto medan',
			'Kuah soto medan',
			'Kuah soto medan',
			'Kuah soto medan',
			'Kuah soto medan',
			'Kuah soto medan',
			'Bergedel kentang',
			'Bergedel kentang',
			'Bergedel kentang',
			'Bergedel kentang',
			'Bergedel kentang',
			'Bergedel kentang',
			'Bergedel kentang',
			'Bergedel kentang',
			'Bergedel kentang',
			'Bergedel kentang',
			'Siomay ayam',
			'Siomay ayam',
			'Siomay ayam',
			'Siomay ayam',
			'Siomay ayam',
			'Siomay ayam',
			'Siomay ayam',
			'Siomay ayam',
			'Siomay ayam',
			'Siomay ayam',
			'Siomay ayam',
			'Siomay ayam',
			'Sambal kecap asin',
			'Sambal kecap asin',
			'Sambel kecap',
			'Sambel kecap',
			'Sambel kecap',
			'Sambel kecap',
			'Sambel kecap',
			'Saus Padang',
			'Saus Padang',
			'Saus Padang',
			'Saus Padang',
			'Saus Padang',
			'Saus Padang',
			'Saus Padang',
			'Saus Padang',
			'Saus Padang',
			'Saus Padang',
			'Bumbu Rujak',
			'Bumbu Rujak',
			'Bumbu Rujak',
			'Bumbu Rujak',
			'Bumbu Rujak',
			'Bumbu Rujak',
			'Bumbu Rujak',
			'Bumbu Rujak',
			'Bumbu Rujak',
			'Bumbu Rujak',
			'Bumbu Rujak',
			'Bumbu Rujak',
			'Bumbu Rujak',
			'Bumbu Rujak',
			'Bumbu Rujak',
			'Tepung kentaky',
			'Tepung kentaky',
			'Tepung kentaky',
			'Tepung kentaky',
			'Tepung kentaky',
			'Tepung kentaky',
			'Tepung kentaky',
			'Tepung kentaky',
			'BBQ sauce',
			'BBQ sauce',
			'BBQ sauce',
			'BBQ sauce',
			'BBQ sauce',
			'BBQ sauce',
			'BBQ sauce',
			'BBQ sauce',
			'BBQ sauce',
			'Bumbu bacem ikan',
			'Bumbu bacem ikan',
			'Bumbu bacem ikan',
			'Bumbu bacem ikan',
			'Bumbu bacem ikan',
			'Bumbu bacem ikan',
			'Sambal pencit',
			'Sambal pencit',
			'Sambal pencit',
			'Sambal pencit',
			'Sambal pencit',
			'Sambal pencit',
			'Sambal pencit',
			'Sambal pencit',
			'Sambal pencit',
			'Sambal Penyetan',
			'Sambal Penyetan',
			'Sambal Penyetan',
			'Sambal Penyetan',
			'Sambal Penyetan',
			'Sambal Penyetan',
			'Sambal Penyetan',
			'Sambal Penyetan',
			'Sambal Penyetan',
			'Sambal Penyetan',
			'Sambal Penyetan',
			'Sambal bawang',
			'Sambal bawang',
			'Sambal bawang',
			'Sambal bawang',
			'Sambal bawang',
			'Sambal bawang',
			'Sambal bawang',
			'Sambal bawang',
			'Lalapan',
			'Lalapan',
			'Lalapan',
			'Lalapan',
			'Telur dadar',
			'Telur dadar',
			'Telur dadar',
			'Telur dadar',
			'Kuah soto Banjar',
			'Kuah soto Banjar',
			'Kuah soto Banjar',
			'Kuah soto Banjar',
			'Kuah soto Banjar',
			'Kuah soto Banjar',
			'Kuah soto Banjar',
			'Kuah soto Banjar',
			'Kuah soto Banjar',
			'Kuah soto Banjar',
			'Kuah soto Banjar',
			'Kuah soto Banjar',
			'Kuah soto Banjar',
			'Kuah soto pekalongan',
			'Kuah soto pekalongan',
			'Kuah soto pekalongan',
			'Kuah soto pekalongan',
			'Kuah soto pekalongan',
			'Kuah soto pekalongan',
			'Kuah soto pekalongan',
			'Kuah soto pekalongan',
			'Kuah soto pekalongan',
			'Kuah soto pekalongan',
			'Kuah soto pekalongan',
			'Kuah soto pekalongan',
			'Kuah soto pekalongan',
			'Saus keju',
			'Saus keju',
			'Saus keju',
			'Saus keju',
			'Saus keju',
			'Saus keju',
			'Saus keju',
			'Saus keju',
			'Saus keju',
			'Saus keju',
			'Saus keju',
			'Saus keju',
			'Saus keju',
			'Saus keju',
			'Saus keju',
			'Sambel Colo Colo',
			'Sambel Colo Colo',
			'Sambel Colo Colo',
			'Sambel Colo Colo',
			'Sambel Colo Colo',
			'Sambel Colo Colo',
			'Sambel Colo Colo',
			'Saus telur asin',
			'Saus telur asin',
			'Saus telur asin',
			'Saus telur asin',
			'Saus telur asin',
			'Saus telur asin',
			'Saus telur asin',
			'Saus telur asin',
			'Saus telur asin',
			'Saus telur asin',
			'Sambel kecobrang',
			'Sambel kecobrang',
			'Sambel kecobrang',
			'Sambel kecobrang',
			'Sambel kecobrang',
			'Sambel kecobrang',
			'Sambel kecobrang',
			'Sambel kecobrang',
			'Sambel kecobrang',
			'Sambel kecobrang',
			'Black pepper sauce western',
			'Black pepper sauce western',
			'Black pepper sauce western',
			'Black pepper sauce western',
			'Black pepper sauce western',
			'Black pepper sauce western',
			'Black pepper sauce western',
			'Black pepper sauce western',
			'Black pepper sauce western',
			'Black pepper sauce western',
			'Sausage skewer',
			'Sausage skewer',
			'Sausage skewer',
			'Sausage skewer',
			'Seafood skewer',
			'Seafood skewer',
			'Seafood skewer',
			'Seafood skewer',
			'Seafood skewer',
			'Seafood skewer',
			'Bumbu kalio',
			'Bumbu kalio',
			'Bumbu kalio',
			'Bumbu kalio',
			'Bumbu kalio',
			'Bumbu kalio',
			'Bumbu kalio',
			'Bumbu kalio',
			'Bumbu kalio',
			'Bumbu kalio',
			'Bumbu bebek',
			'Bumbu bebek',
			'Bumbu bebek',
			'Bumbu bebek',
			'Bumbu bebek',
			'Bumbu bebek',
			'Saus mie asam pedas',
			'Saus mie asam pedas',
			'Saus mie asam pedas',
			'Saus mie asam pedas',
			'Saus mie asam pedas',
			'Sambal petis',
			'Sambal petis',
			'Sambal petis',
			'Sambal petis',
			'Sambal petis',
			'Bawang goreng wayin',
			'Bawang goreng wayin',
			'Bawang goreng wayin',
			'Bawang goreng wayin',
			'Bawang goreng wayin',
			'Kuah ayam',
			'Kuah ayam',
			'Kuah ayam',
			'Kuah ayam',
			'Kuah ayam',
			'Kuah ayam',
			'Bumbu kikil',
			'Bumbu kikil',
			'Bumbu kikil',
			'Bumbu kikil',
			'Bumbu kikil',
			'Bumbu kikil',
			'Bumbu kikil',
			'Bumbu kikil',
			'Bumbu kikil',
			'Bumbu kikil',
			'Ayam bumbu kuning',
			'Ayam bumbu kuning',
			'Ayam bumbu kuning',
			'Ayam bumbu kuning',
			'Ayam bumbu kuning',
			'Ayam bumbu kuning',
			'Roux',
			'Roux',
			'Plum Sauce',
			'Plum Sauce',
			'Plum Sauce',
			'Plum Sauce',
			'Plum Sauce',
			'Plum Sauce',
			'Plum Sauce',
			'Plum Sauce',
			'Tahu isi Ayam Jamur',
			'Tahu isi Ayam Jamur',
			'Tahu isi Ayam Jamur',
			'Tahu isi Ayam Jamur',
			'Tahu isi Ayam Jamur',
			'Tahu isi Ayam Jamur',
			'Tahu isi Ayam Jamur',
			'Tahu isi Ayam Jamur',
			'Tahu isi Ayam Jamur',
			'Tahu isi Ayam Jamur',
			'Tahu isi Ayam Jamur',
			'Tahu isi Ayam Jamur',
			'Tahu isi Ayam Jamur',
			'Serundeng lengkuas',
			'Serundeng lengkuas',
			'Serundeng lengkuas',
			'Serundeng lengkuas',
			'Serundeng lengkuas',
			'Bumbu opor',
			'Bumbu opor',
			'Bumbu opor',
			'Bumbu opor',
			'Bumbu opor',
			'Bumbu opor',
			'Bumbu opor',
			'Bumbu opor',
			'Bumbu opor',
			'Bumbu opor',
			'Bumbu opor',
			'Bumbu opor',
			'Bumbu bacem',
			'Bumbu bacem',
			'Bumbu bacem',
			'Bumbu bacem',
			'Bumbu bacem',
			'Bumbu bacem',
			'Bumbu bacem',
			'Bumbu bacem',
			'Bumbu bacem',
			'Bumbu bacem',
			'Bumbu bacem',
			'Bumbu bacem',
			'Paket rebusan',
			'Paket rebusan',
			'Paket rebusan',
			'Saus Orange',
			'Saus Orange',
			'Saus Orange',
			'Saus Orange',
			'Sinom',
			'Sinom',
			'Sinom',
			'Sinom',
			'Sinom',
			'Mayo keju',
			'Mayo keju',
			'Mayo keju',
			'Mayo keju',
			'Mayo keju',
			'Mayo keju',
			'Mayo keju',
			'Mayo keju',
			'Empal',
			'Empal',
			'Empal',
			'Empal',
			'Empal',
			'Empal',
			'Empal',
			'Empal',
			'Empal',
			'Bumbu seblak',
			'Bumbu seblak',
			'Bumbu seblak',
			'Bumbu seblak',
			'Bumbu seblak',
			'Bumbu seblak',
			'Bumbu seblak',
			'Saus Toban djan',
			'Saus Toban djan',
			'Saus Toban djan',
			'Saus Toban djan',
			'Saus Toban djan',
			'Saus Toban djan',
			'Saus Toban djan',
			'Saus Toban djan',
			'Saus Toban djan',
			'Saus Toban djan',
			'Saus Toban djan',
			'Saus Toban djan',
			'Kaldu Ayam',
			'Kaldu Ayam',
			'Kaldu Ayam',
			'Kaldu Ayam',
			'Kaldu Ayam',
			'Saus Thailand',
			'Saus Thailand',
			'Saus Thailand',
			'Saus Thailand',
			'Saus Thailand',
			'Saus Thailand',
			'Saus Thailand',
			'Saus Thailand',
			'Saus Thailand',
			'Saus Thailand',
			'Saus Thailand',
			'Saus Teriyaki',
			'Saus Teriyaki',
			'Saus Teriyaki',
			'Saus Teriyaki',
			'Saus Teriyaki',
			'Saus Teriyaki',
			'Saus Teriyaki',
			'Saus Teriyaki',
			'Saus Teriyaki',
			'Saus Teriyaki',
			'Saus Teriyaki',
			'Tepung Campur',
			'Tepung Campur',
			'Tepung Campur',
			'Tepung Campur',
			'Tepung Campur',
			'Tepung Campur',
			'Tepung Campur',
			'Bakso',
			'Bakso',
			'Bakso',
			'Bakso',
			'Bakso',
			'Bakso',
			'Bakso',
			'Bakso',
			'Siomay',
			'Siomay',
			'Siomay',
			'Siomay',
			'Siomay',
			'Siomay',
			'Siomay',
			'Siomay',
			'Siomay',
			'Tahu bakso',
			'Tahu bakso',
			'Tahu bakso',
			'Tahu bakso',
			'Tahu bakso',
			'Tahu bakso',
			'Tahu bakso',
			'Tahu bakso',
			'Tahu bakso',
			'Saus Mushroom',
			'Saus Mushroom',
			'Saus Mushroom',
			'Saus Mushroom',
			'Saus Mushroom',
			'Saus Mushroom',
			'Saus Mushroom',
			'Saus Mushroom',
			'Saus Mushroom',
			'Saus Mushroom',
			'Saus Mushroom',
			'Saus Mushroom',
			'Saus Mushroom',
			'Saus mie',
			'Saus mie',
			'Saus mie',
			'Saus mie',
			'Saus mie',
			'Saus mie',
			'Saus mie',
			'Acar',
			'Acar',
			'Acar',
			'Acar',
			'Acar',
			'Sambel soto',
			'Sambel soto',
			'Sambel soto',
			'Sambel bajak',
			'Sambel bajak',
			'Sambel bajak',
			'Sambel bajak',
			'Sambel bajak',
			'Sambel bajak',
			'Sambel bajak',
			'Sambel bajak',
			'Sambel bajak',
			'Bumbu Siomay',
			'Bumbu Siomay',
			'Bumbu Siomay',
			'Bumbu Siomay',
			'Bumbu Siomay',
			'Bumbu Siomay',
			'Bumbu Siomay',
			'Bumbu Siomay',
			'Bumbu Siomay',
			'Bumbu xo',
			'Bumbu xo',
			'Bumbu xo',
			'Bumbu xo',
			'Bumbu xo',
			'Bumbu xo',
			'Bumbu xo',
			'Bumbu xo',
			'Bumbu xo',
			'Bumbu xo',
			'Sambel dabu dabu',
			'Sambel dabu dabu',
			'Sambel dabu dabu',
			'Sambel dabu dabu',
			'Sambel dabu dabu',
			'Sambel dabu dabu',
			'Sambal hongkong',
			'Sambal hongkong',
			'Sambal hongkong',
			'Sambal hongkong',
			'Sambal hongkong',
			'Sambal hongkong',
			'Sambal hongkong',
			'Sambal hongkong',
			'Sambal hongkong',
			'Sambal hongkong',
			'Saus cah',
			'Saus cah',
			'Saus cah',
			'Saus cah',
			'Saus cah',
			'Saus cah',
			'Saus cah',
			'Saus cah',
			'Saus black papper',
			'Saus black papper',
			'Saus black papper',
			'Saus black papper',
			'Saus black papper',
			'Saus black papper',
			'Saus black papper',
			'Saus kanton',
			'Saus kanton',
			'Saus kanton',
			'Saus kanton',
			'Saus kanton',
			'Saus Beajing',
			'Saus Beajing',
			'Saus Beajing',
			'Saus Beajing',
			'Saus Beajing',
			'Saus Beajing',
			'Saus cabe kering',
			'Saus cabe kering',
			'Saus cabe kering',
			'Saus cabe kering',
			'Saus cabe kering',
			'Saus cabe kering',
			'Saus cabe kering',
			'Saus Jahe',
			'Saus Jahe',
			'Saus Jahe',
			'Saus Jahe',
			'Saus Jahe',
			'Saus Jahe',
			'Saus Jahe',
			'Saus Jahe',
			'Saus Rempah',
			'Saus Rempah',
			'Saus Rempah',
			'Saus Rempah',
			'Saus Rempah',
			'Saus Rempah',
			'Saus Rempah',
			'Saus Rempah',
			'Saus Rempah',
			'Saus Rempah',
			'Saus Rempah',
			'Saus Rempah',
			'Saus Rempah',
			'Tepung tahu isi',
			'Tepung tahu isi',
			'Tepung tahu isi',
			'Tepung tahu isi',
			'Tepung tahu isi',
			'Tepung tahu isi',
			'Tepung tahu isi',
			'Tepung tahu isi',
			'Saus Teluk',
			'Saus Teluk',
			'Saus Teluk',
			'Saus Teluk',
			'Saus Teluk',
			'Saus Teluk',
			'Saus Teluk',
			'Saus Teluk',
			'Saus Teluk',
			'Bumbu Wayin',
			'Bumbu Wayin',
			'Bumbu Wayin',
			'Bumbu Wayin',
			'Bumbu Wayin',
			'Bumbu Wayin',
			'Bumbu Wayin',
			'Bumbu Wayin',
			'Bumbu rica-rica',
			'Bumbu rica-rica',
			'Bumbu rica-rica',
			'Bumbu rica-rica',
			'Bumbu rica-rica',
			'Bumbu rica-rica',
			'Bumbu rica-rica',
			'Bumbu rica-rica',
			'Bumbu rica-rica',
			'Bumbu rica-rica',
			'Bumbu rica-rica',
			'Bumbu rica-rica',
			'Bumbu rica-rica',
			'Kuah Somen',
			'Kuah Somen',
			'Kuah Somen',
			'Kuah Somen',
			'Kuah Rawon',
			'Kuah Rawon',
			'Kuah Rawon',
			'Kuah Rawon',
			'Kuah Rawon',
			'Kuah Rawon',
			'Kuah Rawon',
			'Kuah Rawon',
			'Kuah Rawon',
			'Kuah Rawon',
			'Kuah Rawon',
			'Kuah Rawon',
			'Kuah soto ayam',
			'Kuah soto ayam',
			'Kuah soto ayam',
			'Kuah soto ayam',
			'Kuah soto ayam',
			'Kuah soto ayam',
			'Kuah soto ayam',
			'Kuah soto ayam',
			'Kuah soto ayam',
			'Kuah soto ayam',
			'Kuah soto ayam',
			'Kuah soto ayam',
			'Bumbu Kuning',
			'Bumbu Kuning',
			'Bumbu Kuning',
			'Bumbu Kuning',
			'Bumbu Kuning',
			'Bumbu Kuning',
			'Kuah telor orak arik',
			'Kuah telor orak arik',
			'Kuah telor orak arik',
			'Kuah telor orak arik',
			'Kuah telor orak arik',
			'Kuah telor orak arik',
			'Kuah telor orak arik',
			'Kuah telor orak arik',
			'Kuah telor orak arik',
			'Kuah Buntut',
			'Kuah Buntut',
			'Kuah Buntut',
			'Kuah Buntut',
			'Kuah Buntut',
			'Kuah Buntut',
			'Kuah Buntut',
			'Kuah Buntut',
			'Kuah Buntut',
			'Kuah Buntut',
			'Tomato Concase',
			'Tomato Concase',
			'Tomato Concase',
			'Tomato Concase',
			'Tomato Concase',
			'Tomato Concase',
			'Tomato Concase',
			'Tomato Concase',
			'Tomato Concase',
			'Tomato Concase',
			'Mashroom saus',
			'Mashroom saus',
			'Mashroom saus',
			'Mashroom saus',
			'Mashroom saus',
			'Mashroom saus',
			'Mashroom saus',
			'Mashroom saus',
			'Mashroom saus',
			'Mashroom saus',
			'Mashroom saus',
			'Gravy sauce',
			'Gravy sauce',
			'Gravy sauce',
			'Gravy sauce',
			'Gravy sauce',
			'Gravy sauce',
			'Gravy sauce',
			'Gravy sauce',
			'Gravy sauce',
			'Gravy sauce',
			'Gravy sauce',
			'Rosemary sauce',
			'Rosemary sauce',
			'Rosemary sauce',
			'Rosemary sauce',
			'Rosemary sauce',
			'Rosemary sauce',
			'Rosemary sauce',
			'Rosemary sauce',
			'Rosemary sauce',
			'Rosemary sauce',
			'Rosemary sauce',
			'Dough pizza',
			'Dough pizza',
			'Dough pizza',
			'Dough pizza',
			'Dough pizza',
			'Dough pizza',
			'Dough pizza',
			'Dough pizza',
			'Roti tawar',
			'Roti tawar',
			'Roti tawar',
			'Roti tawar',
			'Roti tawar',
			'Roti tawar',
			'Roti tawar',
			'Roti tawar',
			'Tar - tar saus',
			'Tar - tar saus',
			'Tar - tar saus',
			'Tar - tar saus',
			'Tar - tar saus',
			'Tar - tar saus',
			'Sambal balado',
			'Sambal balado',
			'Sambal balado',
			'Sambal balado',
			'Sambal balado',
			'Sambal balado',
			'bumbu taliwang',
			'bumbu taliwang',
			'bumbu taliwang',
			'bumbu taliwang',
			'bumbu taliwang',
			'bumbu taliwang',
			'bumbu taliwang',
			'Bumbu Sate',
			'Bumbu Sate',
			'Bumbu Sate',
			'Bumbu Sate',
			'Saus Aroma',
			'Saus Aroma',
			'Saus Aroma',
			'Saus Aroma',
			'Saus Aroma',
			'Saus Aroma',
			'Saus Aroma',
			'Saus Aroma',
			'Saus Aroma',
			'Saus Aroma',
			'Saus Aroma',
			'Saus Aroma',
			'Saus Aroma',
			'Tahu Bakso Buat',
			'Tahu Bakso Buat',
			'Pangsit Goreng',
			'Pangsit Goreng',
			'Adonan lumpia kucai',
			'Adonan lumpia kucai',
			'Adonan lumpia kucai',
			'Adonan lumpia kucai',
			'Adonan lumpia kucai',
			'Adonan lumpia kucai',
			'Adonan lumpia kucai',
			'Adonan lumpia kucai',
			'Adonan lumpia kucai',
			'Adonan lumpia kucai',
			'Adonan lumpia kucai',
			'Adonan Udang',
			'Adonan Udang',
			'Adonan Udang',
			'Adonan Udang',
			'Adonan Udang',
			'Adonan Udang',
			'Adonan Udang',
			'Adonan Udang',
			'Adonan Udang',
			'Saus Asam manis',
			'Saus Asam manis',
			'Saus Asam manis',
			'Saus Asam manis',
			'Saus Asam manis',
			'Saus Asam manis',
			'Saus Asam manis',
			'Saus Asam manis',
			'Saus Asam manis',
			'Saus Asam manis',
			'Saus Asam manis',
			'Kuah soto medan',
			'Kuah soto medan',
			'Kuah soto medan',
			'Kuah soto medan',
			'Kuah soto medan',
			'Kuah soto medan',
			'Kuah soto medan',
			'Kuah soto medan',
			'Kuah soto medan',
			'Kuah soto medan',
			'Kuah soto medan',
			'Kuah soto medan',
			'Bergedel kentang',
			'Bergedel kentang',
			'Bergedel kentang',
			'Bergedel kentang',
			'Bergedel kentang',
			'Bergedel kentang',
			'Bergedel kentang',
			'Bergedel kentang',
			'Bergedel kentang',
			'Bergedel kentang',
			'Siomay ayam',
			'Siomay ayam',
			'Siomay ayam',
			'Siomay ayam',
			'Siomay ayam',
			'Siomay ayam',
			'Siomay ayam',
			'Siomay ayam',
			'Siomay ayam',
			'Siomay ayam',
			'Siomay ayam',
			'Siomay ayam',
			'Sambal kecap asin',
			'Sambal kecap asin',
			'Sambel kecap',
			'Sambel kecap',
			'Sambel kecap',
			'Sambel kecap',
			'Sambel kecap',
			'Saus Padang',
			'Saus Padang',
			'Saus Padang',
			'Saus Padang',
			'Saus Padang',
			'Saus Padang',
			'Saus Padang',
			'Saus Padang',
			'Saus Padang',
			'Saus Padang',
			'Bumbu Rujak',
			'Bumbu Rujak',
			'Bumbu Rujak',
			'Bumbu Rujak',
			'Bumbu Rujak',
			'Bumbu Rujak',
			'Bumbu Rujak',
			'Bumbu Rujak',
			'Bumbu Rujak',
			'Bumbu Rujak',
			'Bumbu Rujak',
			'Bumbu Rujak',
			'Bumbu Rujak',
			'Bumbu Rujak',
			'Bumbu Rujak',
			'Tepung kentaky',
			'Tepung kentaky',
			'Tepung kentaky',
			'Tepung kentaky',
			'Tepung kentaky',
			'Tepung kentaky',
			'Tepung kentaky',
			'Tepung kentaky',
			'BBQ sauce',
			'BBQ sauce',
			'BBQ sauce',
			'BBQ sauce',
			'BBQ sauce',
			'BBQ sauce',
			'BBQ sauce',
			'BBQ sauce',
			'BBQ sauce',
			'Bumbu bacem ikan',
			'Bumbu bacem ikan',
			'Bumbu bacem ikan',
			'Bumbu bacem ikan',
			'Bumbu bacem ikan',
			'Bumbu bacem ikan',
			'Sambal pencit',
			'Sambal pencit',
			'Sambal pencit',
			'Sambal pencit',
			'Sambal pencit',
			'Sambal pencit',
			'Sambal pencit',
			'Sambal pencit',
			'Sambal pencit',
			'Sambal Penyetan',
			'Sambal Penyetan',
			'Sambal Penyetan',
			'Sambal Penyetan',
			'Sambal Penyetan',
			'Sambal Penyetan',
			'Sambal Penyetan',
			'Sambal Penyetan',
			'Sambal Penyetan',
			'Sambal Penyetan',
			'Sambal Penyetan',
			'Sambal bawang',
			'Sambal bawang',
			'Sambal bawang',
			'Sambal bawang',
			'Sambal bawang',
			'Sambal bawang',
			'Sambal bawang',
			'Sambal bawang',
			'Lalapan',
			'Lalapan',
			'Lalapan',
			'Lalapan',
			'Telur dadar',
			'Telur dadar',
			'Telur dadar',
			'Telur dadar',
			'Kuah soto Banjar',
			'Kuah soto Banjar',
			'Kuah soto Banjar',
			'Kuah soto Banjar',
			'Kuah soto Banjar',
			'Kuah soto Banjar',
			'Kuah soto Banjar',
			'Kuah soto Banjar',
			'Kuah soto Banjar',
			'Kuah soto Banjar',
			'Kuah soto Banjar',
			'Kuah soto Banjar',
			'Kuah soto Banjar',
			'Kuah soto pekalongan',
			'Kuah soto pekalongan',
			'Kuah soto pekalongan',
			'Kuah soto pekalongan',
			'Kuah soto pekalongan',
			'Kuah soto pekalongan',
			'Kuah soto pekalongan',
			'Kuah soto pekalongan',
			'Kuah soto pekalongan',
			'Kuah soto pekalongan',
			'Kuah soto pekalongan',
			'Kuah soto pekalongan',
			'Kuah soto pekalongan',
			'Saus keju',
			'Saus keju',
			'Saus keju',
			'Saus keju',
			'Saus keju',
			'Saus keju',
			'Saus keju',
			'Saus keju',
			'Saus keju',
			'Saus keju',
			'Saus keju',
			'Saus keju',
			'Saus keju',
			'Saus keju',
			'Saus keju',
			'Sambel Colo Colo',
			'Sambel Colo Colo',
			'Sambel Colo Colo',
			'Sambel Colo Colo',
			'Sambel Colo Colo',
			'Sambel Colo Colo',
			'Sambel Colo Colo',
			'Saus telur asin',
			'Saus telur asin',
			'Saus telur asin',
			'Saus telur asin',
			'Saus telur asin',
			'Saus telur asin',
			'Saus telur asin',
			'Saus telur asin',
			'Saus telur asin',
			'Saus telur asin',
			'Sambel kecobrang',
			'Sambel kecobrang',
			'Sambel kecobrang',
			'Sambel kecobrang',
			'Sambel kecobrang',
			'Sambel kecobrang',
			'Sambel kecobrang',
			'Sambel kecobrang',
			'Sambel kecobrang',
			'Sambel kecobrang',
			'Black pepper sauce western',
			'Black pepper sauce western',
			'Black pepper sauce western',
			'Black pepper sauce western',
			'Black pepper sauce western',
			'Black pepper sauce western',
			'Black pepper sauce western',
			'Black pepper sauce western',
			'Black pepper sauce western',
			'Black pepper sauce western',
			'Sausage skewer',
			'Sausage skewer',
			'Sausage skewer',
			'Sausage skewer',
			'Seafood skewer',
			'Seafood skewer',
			'Seafood skewer',
			'Seafood skewer',
			'Seafood skewer',
			'Seafood skewer',
			'Bumbu kalio',
			'Bumbu kalio',
			'Bumbu kalio',
			'Bumbu kalio',
			'Bumbu kalio',
			'Bumbu kalio',
			'Bumbu kalio',
			'Bumbu kalio',
			'Bumbu kalio',
			'Bumbu kalio',
			'Bumbu bebek',
			'Bumbu bebek',
			'Bumbu bebek',
			'Bumbu bebek',
			'Bumbu bebek',
			'Bumbu bebek',
			'Saus mie asam pedas',
			'Saus mie asam pedas',
			'Saus mie asam pedas',
			'Saus mie asam pedas',
			'Saus mie asam pedas',
			'Sambal petis',
			'Sambal petis',
			'Sambal petis',
			'Sambal petis',
			'Sambal petis',
			'Bawang goreng wayin',
			'Bawang goreng wayin',
			'Bawang goreng wayin',
			'Bawang goreng wayin',
			'Bawang goreng wayin',
			'Kuah ayam',
			'Kuah ayam',
			'Kuah ayam',
			'Kuah ayam',
			'Kuah ayam',
			'Kuah ayam',
			'Bumbu kikil',
			'Bumbu kikil',
			'Bumbu kikil',
			'Bumbu kikil',
			'Bumbu kikil',
			'Bumbu kikil',
			'Bumbu kikil',
			'Bumbu kikil',
			'Bumbu kikil',
			'Bumbu kikil',
			'Ayam bumbu kuning',
			'Ayam bumbu kuning',
			'Ayam bumbu kuning',
			'Ayam bumbu kuning',
			'Ayam bumbu kuning',
			'Ayam bumbu kuning',
			'Roux',
			'Roux',
			'Plum Sauce',
			'Plum Sauce',
			'Plum Sauce',
			'Plum Sauce',
			'Plum Sauce',
			'Plum Sauce',
			'Plum Sauce',
			'Plum Sauce',
			'Tahu isi Ayam Jamur',
			'Tahu isi Ayam Jamur',
			'Tahu isi Ayam Jamur',
			'Tahu isi Ayam Jamur',
			'Tahu isi Ayam Jamur',
			'Tahu isi Ayam Jamur',
			'Tahu isi Ayam Jamur',
			'Tahu isi Ayam Jamur',
			'Tahu isi Ayam Jamur',
			'Tahu isi Ayam Jamur',
			'Tahu isi Ayam Jamur',
			'Tahu isi Ayam Jamur',
			'Tahu isi Ayam Jamur',
			'Serundeng lengkuas',
			'Serundeng lengkuas',
			'Serundeng lengkuas',
			'Serundeng lengkuas',
			'Serundeng lengkuas',
			'Bumbu opor',
			'Bumbu opor',
			'Bumbu opor',
			'Bumbu opor',
			'Bumbu opor',
			'Bumbu opor',
			'Bumbu opor',
			'Bumbu opor',
			'Bumbu opor',
			'Bumbu opor',
			'Bumbu opor',
			'Bumbu opor',
			'Bumbu bacem',
			'Bumbu bacem',
			'Bumbu bacem',
			'Bumbu bacem',
			'Bumbu bacem',
			'Bumbu bacem',
			'Bumbu bacem',
			'Bumbu bacem',
			'Bumbu bacem',
			'Bumbu bacem',
			'Bumbu bacem',
			'Bumbu bacem',
			'Paket rebusan',
			'Paket rebusan',
			'Paket rebusan',
			'Saus Orange',
			'Saus Orange',
			'Saus Orange',
			'Saus Orange',
			'Sinom',
			'Sinom',
			'Sinom',
			'Sinom',
			'Sinom',
			'Mayo keju',
			'Mayo keju',
			'Mayo keju',
			'Mayo keju',
			'Mayo keju',
			'Mayo keju',
			'Mayo keju',
			'Mayo keju',
			'Empal',
			'Empal',
			'Empal',
			'Empal',
			'Empal',
			'Empal',
			'Empal',
			'Empal',
			'Empal',
			'Bumbu seblak',
			'Bumbu seblak',
			'Bumbu seblak',
			'Bumbu seblak',
			'Bumbu seblak',
			'Bumbu seblak',
			'Bumbu seblak',
			'Saus Toban djan',
			'Saus Toban djan',
			'Saus Toban djan',
			'Saus Toban djan',
			'Saus Toban djan',
			'Saus Toban djan',
			'Saus Toban djan',
			'Saus Toban djan',
			'Saus Toban djan',
			'Saus Toban djan',
			'Saus Toban djan',
			'Saus Toban djan',
			'Kaldu Ayam',
			'Kaldu Ayam',
			'Kaldu Ayam',
			'Kaldu Ayam',
			'Kaldu Ayam'
		);

		$_data = null;
		foreach ($data as $k_data => $v_data) {
			$m_conf = new \Model\Storage\Conf();
			$sql = "
				select * from menu where branch_kode = 'GTR' and nama like '".$v_data."%' and status = 1
			";
			$d_menu = $m_conf->hydrateRaw($sql);

			$nama_menu = '-';
			$kode_menu = '-';
			if ( $d_menu->count() > 0 ) {
				$d_menu = $d_menu->toArray()[0];

				$nama_menu = $d_menu['nama'];
				$kode_menu = $d_menu['kode_menu'];
			}

			$_data[ strtoupper($v_data) ] = array(
				'nama_bom' => strtoupper($v_data),
				'nama_menu' => $nama_menu,
				'kode_menu' => $kode_menu
			);
		}

		ksort($_data);

		cetak_r( $_data );
	}
}